# -*- coding: utf-8 -*-
"""Locator.X Learning Environment — the 50-item curriculum.
Pillars, courses, guides, prerequisites, doctrine mapping.
Original Locator.X material. Topic coverage is standard subject matter in this
field; nothing is adapted from any provider's syllabus."""

DOCTRINE = [
 ("Cash flow before capital gains",
  "A building is judged by what it pays while you hold it, not by what you hope it sells for."),
 ("An asset is something that pays you",
  "The test is whether you can name, source and defend the cash flows before you own it."),
 ("Debt is good only when the building services it",
  "Leverage adds only while the unlevered yield exceeds the all-in cost of the debt."),
 ("The value you can add is the only edge you control",
  "The cycle, the rate and the exit cap belong to somebody else."),
 ("Whatever could not be checked travels with the answer",
  "Every score carries its evidence grade and the count of tests that could not be run."),
 ("Relationships are the deal flow, and goodwill compounds",
  "Terms, access and second chances are priced by who you have been to people, not by your spreadsheet."),
]

PILLARS = [
 ("E", "Emotional equity & relationships", "The foundation. Real estate is a relationship business with a spreadsheet attached; this pillar sits under every other one.", "e"),
 ("F", "Foundations & the Locator.X doctrine", "What a building is, what an asset is, and how to read this platform.", "f"),
 ("N", "The numbers", "Every figure that decides a deal, and what each one hides.", "n"),
 ("A", "The asset", "Property types, valuation, leases and the rent roll.", "a"),
 ("C", "Capital & structure", "Debt, equity, partners and the capital markets behind both.", "c"),
 ("D", "Development & delivery", "Zoning, feasibility, construction and getting it built.", "d"),
 ("V", "Evidence, data & judgment", "How to know what you know, and publish what you do not.", "v"),
 ("M", "Market, practice & the long game", "Where money is going, what is changing, and how it ends.", "m"),
]

# fmt: id, title, kind, promise, modules[], lands, doctrine[], prereq[], status
C = [
# ---------------- E — EMOTIONAL EQUITY & RELATIONSHIPS (foundation, 8) ----------
("E1","Emotional equity: the balance sheet nobody keeps","course",
 "Treat trust as a capital account — it is deposited, drawn down, and it compounds or it does not.",
 ["What emotional equity actually is, and why it is not 'being nice'",
  "The four accounts: counterparties, capital, trades, community",
  "Deposits, withdrawals, and the overdraft you cannot see",
  "Why goodwill compounds faster than money in a small market",
  "Auditing your own balance: a written exercise"],
 "The Record Locker — the same discipline of writing down what happened, applied to people",[5,3],[],"live"),

("E2","The relationship map: who actually moves your deals","course",
 "Draw the eight people who decide whether your next deal happens, and what each of them needs from you.",
 ["The eight actors, and which ones you cannot manage",
  "Mapping influence: who is a gate, who is a bridge",
  "The broker relationship is an information relationship",
  "Lenders remember you longer than they remember the deal",
  "Building the map for your own market"],
 "Investment & development i3 — the eight actors and six gates",[5],["E1"],"live"),

("E3","Trust at speed: how reputation prices your terms","course",
 "Why the same deal gets different terms for different people, and how that gap is earned.",
 ["Predictability is the cheapest advantage in the business",
  "Paying on time and deciding on time as strategy",
  "What a lender's credit memo says about you that you never see",
  "Recovering from a broken commitment",
  "The reputation audit"],
 "Delivering the project p5 — leading people who do not work for you",[5,3],["E1"],"live"),

("E4","The hard conversation: money, delay and bad news","course",
 "The skill that separates operators who survive a bad year from those who do not.",
 ["Deliver bad news early, specific and with a plan",
  "The partner call when a draw is late",
  "Telling a tenant, a lender and a partner the same truth",
  "Scripts you write before you need them",
  "What silence costs"],
 "Delivering the project p7 — the risk register and the trigger written while calm",[5],["E1","E3"],"live"),

("E5","Negotiating for the second deal, not the first","course",
 "Terms are set once; relationships are priced every time. Negotiate for the sequence.",
 ["Interests underneath positions",
  "The anchor, and why the first number outweighs the facts after it",
  "Concessions that cost you nothing and buy a lot",
  "Walking away without closing the door",
  "Writing the term sheet a counterparty can say yes to"],
 "Investor mindset m3 — anchoring at the negotiation table",[5,3],["E1","E2"],"live"),

("E6","Partners, families and the money conversations people avoid","course",
 "Most partnerships fail on unspoken expectations, not on the deal.",
 ["The conversation before the LLC",
  "Money, time and decision rights — say all three out loud",
  "Family capital and the cost of an unwritten deal",
  "The exit conversation you have at the start",
  "Putting it in writing without breaking the relationship"],
 "Investment & development i7 — control rights and the unpriced unknown",[5,1],["E1"],"live"),

("E7","Reading the room: emotion as market information","course",
 "A seller's urgency, a lender's nervousness and a contractor's hesitation are data.",
 ["Motivation is the most valuable unpublished field",
  "What a nervous lender is telling you about the cycle",
  "The contractor who goes quiet",
  "Separating your emotion from their signal",
  "Recording the read so you can check it later"],
 "Evidence & analysis e2 — framing before querying; the coverage floor",[5,4],["E1","E4"],"live"),

("E8","The long game: mentors, referrals and compounding goodwill","guide",
 "How a decade of small deposits becomes deal flow you did not have to chase.",
 ["Being worth mentoring",
  "The referral you earn by sending one first",
  "Community as a portfolio position",
  "What to do when you cannot help",
  "The twenty-year relationship"],
 "The Academy's own case-study discipline — judge the decision, not the outcome",[5],["E1","E3"],"live"),

# ---------------- F — FOUNDATIONS (6) ----------
("F1","How a building pays you","course",
 "Four income streams, and why treating them as interchangeable is the first expensive mistake.",
 ["Cash flow, amortisation, appreciation, tax",
  "Which of the four you control",
  "The order they should decide a purchase",
  "Worked example on a real record"],
 "Foundations f1 — a building pays four different ways",[0,1],["E1"],"live"),

("F2","Asset or liability: the Locator.X test","course",
 "Name, source and defend the cash flows before you own it — or you have a position, not an asset.",
 ["What counts as an asset in this doctrine",
  "The three questions before an offer",
  "Positions that look like assets",
  "Applying the test on the map"],
 "The dashboard's asset / liability verdict",[1,0],["F1"],"live"),

("F3","Income you work for, income the building works for","course",
 "The distinction that decides whether you are buying a job or an asset.",
 ["Active and passive, honestly defined",
  "The management load nobody prices",
  "When self-managing is the value-add",
  "Building toward income that does not need you"],
 "Foundations f3",[1,0],["F2"],"live"),

("F4","Your buy box as a statement of who you are","course",
 "A filter with no edge behind any line is a wish list. Write one you can defend.",
 ["Every line traced to an advantage you actually hold",
  "Market, price band, unit count, condition, hold",
  "The written no, and why it is worth as much as the yes",
  "Testing the box against a live market"],
 "The Underwrite tab's buy box and the N-of-Y counter",[3,1],["F2"],"live"),

("F5","Reading Locator.X: score, evidence grade, coverage","guide",
 "How to read every number this platform shows you, including the ones it refuses to show.",
 ["The ten-modality score and the 15% coverage floor",
  "Evidence grades A/B/C/D and the two ceilings",
  "meets / fails / unknown",
  "What a low coverage figure is telling you"],
 "The Evidence and Standard tabs",[4],[],"live"),

("F6","From curiosity to first offer: the 90-day path","guide",
 "A sequenced plan that ends in a written offer, not in more reading.",
 ["Weeks 1-3: doctrine, buy box, market choice",
  "Weeks 4-7: underwriting twenty properties badly, then well",
  "Weeks 8-11: relationships — broker, lender, inspector",
  "Week 12: the offer, and the decision memo behind it"],
 "The full underwriting → decision-memo → Record Locker flow",[0,5],["F4","E2"],"live"),

# ---------------- N — THE NUMBERS (7) ----------
("N1","NOI, and the four things people leave out","course",
 "The number every valuation rests on, and the expenses that quietly are not in it.",
 ["What belongs in NOI and what does not",
  "Management, reserves, vacancy, turnover",
  "Seller's NOI vs yours",
  "Rebuilding a broker's number from scratch"],
 "Reading the numbers r1",[0,1],["F1"],"live"),

("N2","Cap rate is a market opinion, not a property fact","course",
 "What a cap rate actually measures, and why the exit one is somebody else's decision.",
 ["Cap rate as a price, not a return",
  "Entry, exit and the spread that is your risk",
  "Why compression is a rates bet",
  "Reading cap rates across a market honestly"],
 "Reading the numbers r2; the Outlook exit assumptions",[0,3],["N1"],"live"),

("N3","Cash-on-cash and DSCR: the two survival numbers","course",
 "The two figures that decide whether you keep the building through a bad year.",
 ["Cash-on-cash and what it is silent about",
  "DSCR, and why the lender sizes to it",
  "The break-even occupancy nobody computes",
  "Stress-testing both"],
 "The break-even solver at DSCR 1.20",[2,0],["N1"],"live"),

("N4","NPV, IRR and the trap of the short hold","course",
 "Why a 31% IRR on nine months and a 14% on seven years are not comparable businesses.",
 ["Discounting, and choosing a rate honestly",
  "IRR's reinvestment assumption",
  "Multiple roots and sign changes",
  "When NPV is the better question"],
 "Investment & development i1; Graduate g2",[0],["N3"],"live"),

("N5","Equity multiple, WACC and beating the money","course",
 "Beating zero is not the test. Beating the capital you used is.",
 ["Equity multiple: scale without time",
  "Blended cost of capital, in the proportions actually used",
  "The 9% return against an 11% cost",
  "Choosing the right metric for the question"],
 "Investment & development i1",[0,2],["N4"],"live"),

("N6","The pro forma that does not lie to you","course",
 "Building a projection whose assumptions are visible, sourced and challengeable.",
 ["Every assumption on its own line, with a source",
  "Growth rates you can defend",
  "The three lines people leave out",
  "A pro forma someone else can audit"],
 "The Underwrite financing sheets",[4,0],["N3","V1"],"live"),

("N7","Sensitivity: which input actually decides","course",
 "Find the one variable that moves the outcome, and whether you control it.",
 ["One-way and two-way sensitivity",
  "The break-even table",
  "Controllable vs market inputs",
  "When a deal is really a rates position"],
 "The Outlook break-even solver",[3],["N6"],"live"),

# ---------------- A — THE ASSET (7) ----------
("A1","Introduction to the real estate industry","guide",
 "Who does what, who pays whom, and where you fit.",
 ["Owners, operators, brokers, lenders, servicers",
  "How each one is compensated",
  "Public and private ownership structures",
  "Where a small operator has an advantage"],
 "The Program tab's tiers and roles",[5],[],"live"),

("A2","The five commercial classes are five different businesses","course",
 "Lease length is the real difference between multifamily, office, retail, industrial and hospitality.",
 ["Lease length as the organising variable",
  "Retail is a credit business wearing a lease",
  "Hospitality is an operating company with a building",
  "Investor postures: core to opportunistic"],
 "Investment & development i2; the use-code map",[1,3],["F1"],"live"),

("A3","Property valuation: three approaches and when each fails","course",
 "Income, sales comparison and cost — and the conditions that break each one.",
 ["The income approach and its cap-rate dependency",
  "Comparable sales where no deed date is published",
  "Replacement cost and what it ignores",
  "Reconciling three answers"],
 "The Comps desk, and why it cannot function in Orleans or EBR",[4,0],["N2"],"live"),

("A4","Reading the lease clause by clause","course",
 "The document where the money actually lives.",
 ["Term, commencement, escalations",
  "Gross, modified gross, NNN and the base-year trick",
  "TI and free rent are capital, not concessions",
  "Options, co-tenancy, go-dark, holdover"],
 "Investment & development i4",[0,1],["A2"],"live"),

("A5","The rent roll you inherit is not the one you underwrote","course",
 "What changes between the offer and the first month of ownership.",
 ["Verifying a rent roll before close",
  "Estoppels and what they catch",
  "Concessions hidden in a schedule",
  "The first ninety days of operations"],
 "Operations o1",[1,0],["A4"],"live"),

("A6","Turnover, WALT and the year the building re-leases itself","course",
 "Rollover arrives with commissions, downtime and capital at the same moment.",
 ["WALT and the rollover schedule",
  "Turnover as the only time the building is honest",
  "Downtime, commissions, and reserves that are a schedule",
  "Planning the capital for the year it lands"],
 "Operations o3; Investment & development i4",[0,3],["A5"],"live"),

("A7","Student housing and conversion stock","course",
 "Buildings whose recorded use is not their best use — and the campus ring that prices them.",
 ["Leasing by the bed is a different business",
  "The campus ring and enrolment denominators",
  "Conversion feasibility from the public record",
  "Where the platform holds 44,893 conversion-class records"],
 "The conversion engine and the campus layer",[3,4],["A2","D2"],"live"),

# ---------------- C — CAPITAL & STRUCTURE (7) ----------
("C1","Coverage is the only leverage test that matters","course",
 "Loan-to-value describes the past. Coverage describes whether you survive.",
 ["Why LTV flatters and coverage does not",
  "Sizing to the payment, not the price",
  "The reserve is the position",
  "Setting your own coverage floor"],
 "Capital c1; the break-even solver",[2],["N3"],"live"),

("C2","What the loan really costs beyond the rate","course",
 "Points, term, amortisation, recourse, prepayment and the covenants nobody reads.",
 ["The all-in cost, computed",
  "Recourse and what it puts at risk",
  "Prepayment penalties and defeasance",
  "Covenants that can call a performing loan"],
 "Leverage l2",[2],["C1"],"live"),

("C3","The lender's triangle: LTV, DSCR and debt yield","course",
 "Three constraints, one binding at a time — and which one changes with the cycle.",
 ["Each test, and what it protects",
  "Why DSCR binds first when rates rise",
  "Debt yield: the one that cannot be structured around",
  "Refinance risk and the maturity wall"],
 "Investment & development i5",[2,3],["C2"],"live"),

("C4","Seller financing and creative terms","course",
 "The seller is a lender you have not asked yet.",
 ["When a seller should prefer paper to cash",
  "Structuring a note that both sides can hold",
  "Wraps, subject-to, and the risks in each",
  "Asking without giving offence"],
 "Capital c2",[2,5],["C1","E5"],"live"),

("C5","Equity partners: pref, promote and the waterfall","course",
 "What a GP is really selling, and where the money actually ends up.",
 ["LP, GP and co-invest",
  "Preferred return: accrues, or accrues and compounds",
  "Promote, hurdles, catch-up, clawback",
  "Control rights, capital calls and dilution"],
 "Investment & development i7",[2,5],["C3","E6"],"live"),

("C6","Real estate capital markets: public and private","course",
 "Where the money that prices your exit actually comes from.",
 ["Private equity, debt funds, banks and agencies",
  "REITs and what public pricing reveals",
  "Why cap rates track the ten-year",
  "Reading the capital cycle from where you stand"],
 "Graduate g4",[3,0],["C3"],"live"),

("C7","Securitisation: how a mortgage becomes a security","guide",
 "The plumbing behind commercial lending, and why it decides your terms.",
 ["Pooling, tranching and the rating",
  "CMBS servicing and why a special servicer is different",
  "What securitisation does to flexibility",
  "Signals from the issuance market"],
 "Graduate g4",[3],["C6"],"live"),

# ---------------- D — DEVELOPMENT & DELIVERY (7) ----------
("D1","The development system: eight actors, six gates","course",
 "Sequencing cheap reversible steps ahead of expensive irreversible ones.",
 ["The eight parties and what each optimises",
  "Site control, feasibility, entitlement, financing, construction, stabilisation",
  "Money spent before a gate is at risk of everything after it",
  "Shreveport, from the public record"],
 "Investment & development i3; Delivering p1",[3,5],["F1","E2"],"live"),

("D2","Zoning: density, height and coverage are three limits","course",
 "Three separate constraints that people collapse into one word.",
 ["FAR, height, lot coverage, setbacks, parking",
  "Which limit actually binds your site",
  "Overlays and the rules on top of the rules",
  "Reading a zoning table against a real parcel"],
 "Zoning z1 and z3; the evidence ceiling of 55",[3,4],["F1"],"live"),

("D3","By right, conditional, and the word that costs a year","course",
 "The entitlement gate has the longest tail and the least control.",
 ["By right vs discretionary",
  "The hearing calendar as a cost line",
  "Community process, honestly",
  "Pricing entitlement risk you do not control"],
 "Zoning z2; Delivering p1",[3],["D2","E7"],"live"),

("D4","Feasibility as a gate, not an opinion","course",
 "Residual land value, and kill criteria written before the model runs.",
 ["Residual land value forwards and backwards",
  "Writing kill criteria in advance",
  "Cost failure vs exit-cap failure",
  "The zoning-only ceiling and what it means for a study"],
 "Investment & development i6",[3,4],["D2","N7"],"live"),

("D5","Construction cost, schedule and the contingency","course",
 "The schedule is a cost line, and the contingency has an owner or it is already spent.",
 ["Cost per square foot, and what it hides",
  "The schedule as carrying cost",
  "Change orders and incomplete design",
  "Contingency release by phase"],
 "Construction b1-b3; Delivering p7; the Rebuild cost anchors",[3],["D4"],"live"),

("D6","Value engineering is not cost cutting","course",
 "One keeps the function and changes the method. The other removes the function.",
 ["The distinction, and why it collapses under pressure",
  "The trade-off register: dollars, function, who bears it",
  "Life-cycle cost vs first cost",
  "Savings that reappear in the exit cap"],
 "Delivering p4",[3],["D5"],"live"),

("D7","The development lab: one site, start to finish","course",
 "A single parcel carried through all six gates, with the arithmetic at each.",
 ["Choosing and controlling the site",
  "Feasibility and the go/no-go",
  "Entitlement strategy and the stakeholder map",
  "Capital stack, construction plan and stabilisation",
  "The decision memo and the post-project review"],
 "The full Underwrite → conversion engine → Outlook chain",[3,1,5],["D5","D6","C5","E2"],"live"),

# ---------------- V — EVIDENCE, DATA & JUDGMENT (5) ----------
("V1","Framing the question before you touch the data","course",
 "The most expensive errors are correct answers to questions nobody needed.",
 ["What decision does this change?",
  "What would change my mind?",
  "The population question comes first",
  "Coverage travels with the screen"],
 "Evidence & analysis e2; the per-signal coverage chart",[4],["F5"],"live"),

("V2","Keys, joins and the duplicate that doubles your market","course",
 "A key that is not unique will silently multiply your rows.",
 ["Why public parcel keys are not unique",
  "Bossier, Onondaga and Guilford, in detail",
  "Inner joins and the population you silently dropped",
  "Verifying counts across every join"],
 "Evidence & analysis e3",[4],["V1"],"live"),

("V3","Medians, skew and the sample-size floor","course",
 "On right-skewed price data the mean is a tail and the median is a market.",
 ["Why every headline figure here is a median",
  "Dispersion, and two populations in one histogram",
  "The floor below which you decline to report",
  "Intervals, and the honest null"],
 "Evidence & analysis e4; the Patterns panel's Wilson intervals",[4],["V1"],"live"),

("V4","Fitting, holding out and refusing to extrapolate","course",
 "Search on one deterministic half, measure on the other, cap what you compound.",
 ["Why the split must not be re-rollable",
  "Simple beats clever on short noisy series",
  "The ±10%/yr cap and the error that produced it",
  "Three modelling errors, published"],
 "Evidence & analysis e5; Predictions and Outlook",[4],["V3"],"live"),

("V5","Drawing a number so it cannot mislead","course",
 "A chart is an argument made in geometry.",
 ["One axis, never two",
  "Colour follows the entity, never its rank",
  "Colour-blind safety is computed, not judged",
  "Density without hiding data"],
 "Evidence & analysis e7; the validated palette",[4],["V3"],"live"),

# ---------------- M — MARKET, PRACTICE & THE LONG GAME (3) ----------
("M1","Markets, jobs and where the money is going","course",
 "From an announcement to a rent, and how long that actually takes.",
 ["Employment, migration and absorption",
  "Supply is the thing that kills the thesis",
  "Announcements that die, and carrying them at zero",
  "Reading the corridor screens honestly"],
 "Markets m1-m3; the corporate projects layer",[3,4],["F1"],"live"),

("M2","Disruption in commercial real estate","guide",
 "What is actually changing in how space is used, financed and priced.",
 ["Remote work and the office question",
  "Logistics, last mile and industrial demand",
  "Climate, insurance and the cost of place",
  "Technology in underwriting: what helps and what flatters"],
 "Graduate g6 — climate risk in underwriting",[3,4],["M1"],"live"),

("M3","Holding, tax and the exit","course",
 "Depreciation, recapture, and why the exit is priced by the next buyer's debt.",
 ["Depreciation and what it does to returns",
  "Recapture and the tax at the end",
  "Exchange mechanics, in general terms",
  "Deciding to sell, refinance or hold"],
 "Holding, tax & exit t1-t2",[0,2],["N5","C3"],"live"),
]

PATHWAYS = [
 ("First deal","For someone who has never owned an investment property. Ends in a written offer.",
  ["E1","F1","F2","F3","N1","N3","F4","A4","C1","E5","E2","F6"]),
 ("The developer","Site control through stabilisation, with the relationship work that carries it.",
  ["E1","E2","F1","D1","D2","D3","N7","D4","D5","D6","C5","E4","D7"]),
 ("The analyst","Judgment and evidence discipline for someone who has to defend a number.",
  ["F5","V1","N1","N2","N4","V2","V3","V4","V5","N6","A3"]),
 ("The partner","For anyone raising or deploying other people's money.",
  ["E1","E6","F2","N3","N5","C1","C3","C5","C6","E4","E3","M3"]),
]

# ---------------------------------------------------------------- LEVELS
LEVELS = [
 (1,"Foundation","Understand what you are looking at",
  "Read a building, a record and a screen. Nothing here requires capital.",
  "You can state the asset test in your own words and read any Locator.X record — score, evidence grade and coverage — without help.",
  ["E1","E2","F1","F2","F3","F5","N1","N2","A1","A2"]),
 (2,"Practitioner","Underwrite, and make an offer you can defend",
  "From a listing to a written offer with the arithmetic behind it.",
  "You can underwrite a property from the public record, size it against a buy box, and produce a decision memo someone else could audit.",
  ["E3","E5","F4","F6","N3","N4","A3","A4","A5","C1","C2","V1","M1"]),
 (3,"Operator","Own it, finance it, run it, change it",
  "Debt, leases, operations and the first two development gates.",
  "You can structure debt against a real rent roll, read a lease clause by clause, and carry a small project from site control through entitlement.",
  ["E4","E7","N6","N7","A6","C3","C4","D1","D2","D3","D4","D5","V2","V3"]),
 (4,"Principal","Lead other people's capital, and defend your judgment",
  "Partnerships, full development, and the evidence discipline that survives diligence.",
  "You can raise and structure equity, carry a development through all six gates, and defend every number you publish including what you could not check.",
  ["E6","E8","N5","A7","C5","C6","C7","D6","D7","V4","V5","M2","M3"]),
]

# ---------------------------------------------------------------- FRAMEWORKS
FRAMEWORKS = [
 ("LOCATOR","The deal screen","e",
  "Seven gates every property passes through before it earns an offer. It spells the platform because it is the platform: each letter is a question Locator.X can answer from the public record.",
  [("L","Location & legal capacity","What the record says you may do here — use, zoning, and the ceiling that caps a permission."),
   ("O","Ownership economics","How it pays: cash flow, amortisation, appreciation, tax — and which of the four you control."),
   ("C","Cash flow","Does it pay while you hold it? NOI rebuilt from scratch, not inherited from a broker."),
   ("A","Asset test","Can you name, source and defend the cash flows before you own it? If not, it is a position."),
   ("T","Terms & leverage","Can the building service the debt? Coverage first, then price."),
   ("O","Outlook","What would have to be true for this to clear — against what the market is actually doing."),
   ("R","Record","What could not be checked travels with the answer. The unknown count is part of the decision.")]),

 ("EQUITY","The relationship practice","f",
  "Six practices that build the account every other framework is executed through. Track 17 is one lesson per letter.",
  [("E","Earn it before you need it","Predictability is the cheapest advantage in the business, and you cannot earn it during."),
   ("Q","Questions before positions","A position is what they say they want. An interest is why — and it is usually cheaper to solve."),
   ("U","Understand who decides","Map the eight actors. Mark each a gate or a bridge. Nobody neglects gates; everybody neglects bridges."),
   ("I","Invest first","Deposits made when you wanted nothing are the only ones that count when you do."),
   ("T","Tell the truth early","The same bad news three weeks late is not late news, it is concealed news."),
   ("Y","Yield the small things","Spend what is cheap to you and dear to them. Winning the last point loses the next deal.")]),

 ("BUILD","The delivery discipline","d",
  "Five habits that carry a project through gates you do not fully control.",
  [("B","Budget a contingency with an owner","Undesignated contingency is spent before the phase that needed it."),
   ("U","Understand who holds each risk","A risk with no named owner is remembered occasionally, not managed."),
   ("I","Interrogate the design before you tender","Change orders are incomplete drawings, priced after you lost leverage."),
   ("L","Lead people who do not work for you","Influence, sequence and being worth working for replace authority."),
   ("D","Debrief","Compare the decision to what was knowable then — not the outcome to the target.")]),

 ("PROOF","The evidence discipline","v",
  "Five rules that decide whether a number can be defended six months later.",
  [("P","Population first","Say which records are in before you average them. It moves the answer more than any model choice."),
   ("R","Recompute, never retype","A transcribed figure is maintained forever by memory, and goes quietly false."),
   ("O","One axis, never two","Two scales in one frame let the analyst manufacture the relationship."),
   ("O","Outliers and skew","On right-skewed prices the mean is a tail. The median is the market."),
   ("F","Floor","Below the sample floor, decline to report. Four significant figures on eleven observations is a lie in a confident font.")]),
]

# ---------------------------------------------------------------- BACKING
# Which shipped Academy track(s) actually provide the written lessons for each
# curriculum item. This is the single source of truth for whether an item is
# live: STATUS IS DERIVED FROM THIS, never stored separately, because storing it
# separately is what let E1-E8 and D7 sit marked "designed" after their content
# had already shipped. An item with at least one backing track is live; an item
# with none is designed. There is no third way to say it.
BACKS = {
 'E1':['equity','mindset'], 'E2':['equity'], 'E3':['equity'], 'E4':['equity'],
 'E5':['equity'], 'E6':['equity'], 'E7':['equity'], 'E8':['equity'],
 'F1':['found'], 'F2':['found'], 'F3':['found'], 'F4':['deliver','found'],
 'F5':['evidence'], 'F6':['wider'],
 'N1':['read'], 'N2':['read'], 'N3':['read'], 'N4':['invdev','grad'],
 'N5':['invdev'], 'N6':['wider'], 'N7':['wider'],
 'A1':['wider'], 'A2':['invdev'], 'A3':['wider'], 'A4':['invdev'], 'A5':['ops'],
 'A6':['ops'], 'A7':['ops'],
 'C1':['capital','lev'], 'C2':['lev'], 'C3':['invdev'], 'C4':['capital'],
 'C5':['invdev'], 'C6':['grad'], 'C7':['wider'],
 'D1':['invdev','deliver'], 'D2':['zone'], 'D3':['zone'], 'D4':['invdev'],
 'D5':['build','deliver'], 'D6':['deliver'], 'D7':['lab'],
 'V1':['evidence'], 'V2':['evidence'], 'V3':['evidence'], 'V4':['evidence'],
 'V5':['evidence'],
 'M1':['mkt'], 'M2':['wider'], 'M3':['tax'],
}

# Tracks that exist to support the curriculum without being the primary backing
# of any single item. Declared so the validator can tell "deliberately unmapped"
# apart from "someone forgot".
SUPPORTING_TRACKS = ['cases', 'dd']

def status_of(item_id):
    """The ONLY way to ask whether an item has written content."""
    return 'live' if BACKS.get(item_id) else 'designed'
