#!/usr/bin/env python3
"""build_packet — the closing-file packet, generated from its two sources.

The Academy teaches a transaction as a FILE: documents to demand, clauses to
read, and a contingency for each unknown. This script turns that teaching into
the data the app renders, so the checklist in the Underwriting tab and the
reference page in docs/ can never drift apart or from the course.

Two sources, neither of them this file:

  content/closing_packet.json   the clause families, the document requests and
                                the contingency mapping. Every state-sensitive
                                item is a QUESTION FOR COUNSEL, never a claim
                                about what a state's law says.
  docs/states/README.md         the 50-state quick reference (51 rows — it
                                carries DC too) — foreclosure
                                regime, tax-delinquency mechanics, transfer tax
                                and HFA, each already reviewed and dated there.
                                Parsed, never restated: if that table changes,
                                the packet changes with it.

Outputs (generated, never edited by hand — CLAUDE.md):

  src/packet_data.js      window.LXPACKETDATA, read by src/packet.js
  docs/CLOSING_PACKET.md  the human-readable reference

Usage:
  python3 scripts/build_packet.py            regenerate both outputs
  python3 scripts/build_packet.py --check    fail if either is stale

What this script refuses to do: invent a state fact. It carries exactly the six
columns docs/states/README.md publishes and nothing else, and the per-state
block it emits is a set of questions plus a link to the sourced guide.
"""
import csv
import json
import os
import re
import sys

R = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + '/'
SRC_JSON = R + 'content/closing_packet.json'
STATES_MD = R + 'docs/states/README.md'
CURRIC_CSV = R + 'curriculum/curriculum-50.csv'
OUT_JS = R + 'src/packet_data.js'
OUT_MD = R + 'docs/CLOSING_PACKET.md'

BANNER = ('/* GENERATED by scripts/build_packet.py from content/closing_packet.json\n'
          '   and the 50-state table in docs/states/README.md. Do not edit: run the\n'
          '   script. tests/run.py fails the build if this file is stale. */\n')


def die(msg):
    raise SystemExit('PACKET BUILD STOPPED — ' + msg)


def read_states():
    """The 50-state quick reference, parsed out of the guide that owns it."""
    md = open(STATES_MD, encoding='utf-8').read()
    m = re.search(r'^\| State \| Guide \|.*?$', md, re.M)
    if not m:
        die('the 50-state table header is not in docs/states/README.md — '
            'the packet has no state layer without it')
    rows = []
    for line in md[m.end():].splitlines():
        line = line.strip()
        if not line.startswith('|'):
            if rows:
                break
            continue
        cells = [c.strip() for c in line.strip('|').split('|')]
        if len(cells) != 6 or set(cells[0]) <= set('- '):
            continue
        link = re.match(r'\[([^\]]+)\]\(([^)]+)\)', cells[1])
        rows.append({
            'state': cells[0],
            'guide': link.group(1) if link else cells[1],
            'guide_href': link.group(2) if link else None,
            'foreclosure': cells[2],
            'tax_delinquency': cells[3],
            'transfer_tax': cells[4],
            'hfa': cells[5],
        })
    # 51, not 50: the table's title says "50-state" but it carries DC as a row,
    # because DC has a foreclosure regime and an HFA like every other row does.
    # The count is asserted so a silently truncated parse cannot ship.
    if len(rows) != 51:
        die('the state table parsed to %d rows, not 51 (50 states + DC) — '
            'refusing to ship a partial state layer' % len(rows))
    return rows


def load_source(states):
    p = json.load(open(SRC_JSON, encoding='utf-8'))
    lessons = {r['ID'] for r in csv.DictReader(open(CURRIC_CSV, encoding='utf-8'))}
    clause_ids = {c['id'] for c in p['clauses']}

    for c in p['clauses']:
        if c['lesson'] not in lessons:
            die('clause %r cites lesson %r, which is not in curriculum-50.csv'
                % (c['id'], c['lesson']))
        if c['state_sensitive'] and not c.get('ask_counsel'):
            die('clause %r is marked state-sensitive but asks counsel nothing — '
                'a state-sensitive item must be a question, never a silence'
                % c['id'])
    for d in p['documents']:
        if d['lesson'] not in lessons:
            die('document %r cites lesson %r, which is not in curriculum-50.csv'
                % (d['id'], d['lesson']))
        if d['resolves'] not in clause_ids:
            die('document %r resolves %r, which is not a clause family'
                % (d['id'], d['resolves']))
        if d['kind'] not in ('public record', 'document', 'quote', 'measurement'):
            die('document %r has kind %r — the four kinds are fixed by '
                'docs/INTEROP.md' % (d['id'], d['kind']))
    # Every contingency must actually resolve something, or it is decoration.
    have = {d['kind'] for d in p['documents']}
    for cg in p['contingencies']:
        if not (set(cg['resolves_kinds']) & have):
            die('contingency %r resolves no kind any document carries' % cg['id'])
    p['states'] = states
    return p


def render_js(p):
    slim = {
        'version': p['version'],
        'reviewed': p['reviewed'],
        'what_this_is': p['what_this_is'],
        'what_this_is_not': p['what_this_is_not'],
        'closing_rule': p['closing_rule'],
        'clauses': p['clauses'],
        'documents': p['documents'],
        'contingencies': p['contingencies'],
        'states': p['states'],
    }
    return BANNER + 'window.LXPACKETDATA=' + json.dumps(
        slim, ensure_ascii=False, separators=(',', ':'), sort_keys=False) + ';\n'


def render_md(p):
    L = []
    A = L.append
    A('# The closing-file packet — generated')
    A('')
    A('<!-- GENERATED by scripts/build_packet.py from content/closing_packet.json and')
    A('     the 50-state table in docs/states/README.md. Do not edit: run the script. -->')
    A('')
    A('**What this is.** ' + p['what_this_is'])
    A('')
    A('**What this is not.** ' + p['what_this_is_not'])
    A('')
    A('Last reviewed: ' + p['reviewed'] + '. The app renders this same data in the')
    A('Underwriting tab, keyed to the edition\'s state and the property\'s asset class;')
    A('[`src/packet.js`](../src/packet.js) is the renderer.')
    A('')
    A('---')
    A('')
    A('## Clause families — what each piece is FOR, and what to ask counsel')
    A('')
    A('Every row below is state-sensitive, which is why the third column is a question')
    A('rather than an answer. This platform does not assert what a state\'s law says')
    A('([`CONTRACT_ANATOMY.md`](CONTRACT_ANATOMY.md)); it gets you to counsel with the')
    A('right question already written down.')
    A('')
    A('| Clause family | What it does | Ask counsel | Course |')
    A('|---|---|---|---|')
    for c in p['clauses']:
        A('| %s | %s | %s | %s |' % (c['family'], c['does'], c['ask_counsel'], c['lesson']))
    A('')
    A('## The document request — by evidence kind')
    A('')
    A('The four kinds are the ones enforced everywhere on this platform')
    A('([`INTEROP.md`](INTEROP.md)). A number\'s kind is where its answer lives, and no')
    A('number may migrate to a stronger kind silently.')
    A('')
    for kind in ('public record', 'document', 'quote', 'measurement'):
        ds = [d for d in p['documents'] if d['kind'] == kind]
        A('### %s (%d)' % (kind, len(ds)))
        A('')
        A('| Item | Asset classes | Why | Resolves | Course |')
        A('|---|---|---|---|---|')
        for d in ds:
            A('| %s | %s | %s | %s | %s |'
              % (d['label'], ', '.join(d['classes']), d['why'], d['resolves'], d['lesson']))
        A('')
    A('## Contingencies — the machinery for resolving unknowns')
    A('')
    for cg in p['contingencies']:
        A('- **%s** — resolves %s. %s'
          % (cg['label'], ' and '.join(cg['resolves_kinds']), cg['note']))
    A('')
    A('> ' + p['closing_rule'])
    A('')
    A('## The state layer')
    A('')
    A('Parsed from the 50-state quick reference in [`states/README.md`](states/README.md)')
    A('— %d rows, because that table carries DC alongside the fifty states —' % len(p['states']))
    A('which carries the sources and the review date. Nothing here is restated or added:')
    A('if a row there changes, this table changes when the script next runs. Four facts')
    A('per state, and the questions above are what you take to a licensed attorney in it.')
    A('')
    A('| State | Guide | Foreclosure | Tax delinquency | Transfer tax | HFA |')
    A('|---|---|---|---|---|---|')
    for s in p['states']:
        guide = ('[%s](states/%s)' % (s['guide'], s['guide_href'])
                 if s['guide_href'] else s['guide'])
        A('| %s | %s | %s | %s | %s | %s |'
          % (s['state'], guide, s['foreclosure'], s['tax_delinquency'],
             s['transfer_tax'], s['hfa']))
    A('')
    A('An edition that spans more than one state resolves to **no state**, and the app')
    A('says so rather than picking one — the packet then shows the universal items and')
    A('names the state-sensitive ones as unanswerable from this record. Unknown is an')
    A('answer.')
    A('')
    return '\n'.join(L)


def main():
    check = '--check' in sys.argv
    p = load_source(read_states())
    outputs = [(OUT_JS, render_js(p)), (OUT_MD, render_md(p))]
    stale = []
    for path, text in outputs:
        cur = open(path, encoding='utf-8').read() if os.path.exists(path) else None
        if cur != text:
            stale.append(os.path.relpath(path, R))
        if not check:
            with open(path, 'w', encoding='utf-8') as f:
                f.write(text)
    if check and stale:
        raise SystemExit(
            'PACKET IS STALE — %s no longer match their sources.\n'
            'Run: python3 scripts/build_packet.py' % ', '.join(stale))
    n_states = len(p['states'])
    print('packet: %d clause families, %d document requests, %d contingencies, '
          '%d states — %s'
          % (len(p['clauses']), len(p['documents']), len(p['contingencies']),
             n_states, 'current' if check else 'written'))


if __name__ == '__main__':
    main()
