#!/usr/bin/env python3
"""Generate src/trades_data.js from crosswalk/trades.json.

The contractor-matching desk reads window.LX_TRADES. That object is a derived
file: the trade taxonomy has ONE source of truth, crosswalk/trades.json, and
this script is the only thing that writes the JS. Regenerate, never patch.

    python3 scripts/gen_trades_js.py          # validate, then write src/trades_data.js
    python3 scripts/gen_trades_js.py --check  # validate, regenerate to a string, exit 1
                                              # if src/trades_data.js differs (a hand edit,
                                              # or a JSON change nobody regenerated after)

Validation raises - never warns - on: a duplicate trade id, a trade missing a
required key, a licence_status outside the file's own status_vocabulary, a
licence_pattern containing a digit (a number is a state fact and state facts
ship only with a source and a date), fewer than four scope_keywords, or a
verify list shorter than three items.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "crosswalk", "trades.json")
OUT = os.path.join(ROOT, "src", "trades_data.js")
HEADER = ("/* GENERATED by scripts/gen_trades_js.py from crosswalk/trades.json "
          "— do not edit */\n")
REQUIRED = ("id", "name", "scope_keywords", "licence_pattern", "licence_status",
            "verify", "source")


def die(msg):
    raise SystemExit("gen_trades_js: " + msg)


def load():
    with open(SRC, encoding="utf-8") as fh:
        return json.load(fh)


def validate(data):
    for key in ("_about", "reviewed", "status_vocabulary", "divisions"):
        if key not in data:
            die("top-level key %r missing" % key)
    vocab = set(data["status_vocabulary"])
    if not vocab:
        die("status_vocabulary is empty")
    seen = {}
    codes = set()
    for div in data["divisions"]:
        for key in ("code", "name", "trades"):
            if key not in div:
                die("division %r missing %r" % (div.get("code") or div.get("name"), key))
        if div["code"] in codes:
            die("duplicate division code %r" % div["code"])
        codes.add(div["code"])
        if not div["trades"]:
            die("division %r has no trades" % div["code"])
        for t in div["trades"]:
            tid = t.get("id", "<no id>")
            missing = [k for k in REQUIRED if k not in t]
            if missing:
                die("trade %r missing %s" % (tid, ", ".join(missing)))
            if not re.fullmatch(r"[a-z][a-z0-9_]*", tid):
                die("trade id %r is not snake_case" % tid)
            if tid in seen:
                die("duplicate trade id %r (divisions %s and %s)"
                    % (tid, seen[tid], div["code"]))
            seen[tid] = div["code"]
            if t["licence_status"] not in vocab:
                die("trade %r: licence_status %r is not in status_vocabulary %s"
                    % (tid, t["licence_status"], sorted(vocab)))
            if re.search(r"\d", t["licence_pattern"]):
                die("trade %r: licence_pattern contains a digit - a number is a state "
                    "fact, and state facts ship only with a source and a date" % tid)
            if not isinstance(t["scope_keywords"], list) or len(t["scope_keywords"]) < 4:
                die("trade %r: fewer than 4 scope_keywords" % tid)
            if not isinstance(t["verify"], list) or len(t["verify"]) < 3:
                die("trade %r: verify list shorter than 3" % tid)
    return len(data["divisions"]), len(seen)


def render(data):
    body = json.dumps(data, ensure_ascii=False, separators=(",", ":"), sort_keys=False)
    return HEADER + "window.LX_TRADES = " + body + ";\n"


def main(argv):
    data = load()
    ndiv, ntr = validate(data)
    js = render(data)
    if "--check" in argv:
        if not os.path.exists(OUT):
            print("gen_trades_js --check: %s does not exist; run without --check"
                  % os.path.relpath(OUT, ROOT))
            return 1
        with open(OUT, encoding="utf-8") as fh:
            current = fh.read()
        if current != js:
            print("gen_trades_js --check: %s is not what crosswalk/trades.json generates - "
                  "it has been hand-edited, or trades.json changed and nobody regenerated. "
                  "Run python3 scripts/gen_trades_js.py" % os.path.relpath(OUT, ROOT))
            return 1
        print("gen_trades_js --check: src/trades_data.js matches crosswalk/trades.json "
              "(%d divisions, %d trades)" % (ndiv, ntr))
        return 0
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(js)
    print("wrote %s (%d divisions, %d trades)" % (os.path.relpath(OUT, ROOT), ndiv, ntr))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
