/* locator.x — research toolbox: subject search, listing extraction, agents, report */
(function(){
'use strict';
const L = () => window.LX; const D = () => window.LXDash;
const $ = (s, el=document) => el.querySelector(s); const $$ = (s, el=document) => Array.from(el.querySelectorAll(s));
const sleep = ms => new Promise(r=>setTimeout(r,ms));
let subject=null, results={}, running=false, sampleFn=undefined, ctl=null;

/* ---------- Claude (sample capability) ---------- */
async function getSample(){ if(sampleFn!==undefined) return sampleFn; try{ if(window.claude && typeof window.claude.use==='function'){ sampleFn = await window.claude.use('sample'); } else sampleFn=null; }catch(e){ sampleFn=null; } return sampleFn; }
getSample().then(s=>{ const b=$('#rai'); if(b) b.classList.toggle('hidden', !s); renderAgents(); });

/* ---------- subject ---------- */
function subjectFrom(l){ subject=l; results={}; renderSubject(); renderAgents(); renderLinks(); $('#report').innerHTML=''; }
function show(){ if(!subject && L().state.sel){ const l=L().allListings().find(x=>x.id===L().state.sel); if(l) subjectFrom(l); } renderLinks(); }
function renderSubject(){
  const X=L(); const box=$('#subject'); if(!subject){ box.innerHTML='<p class="eyebrow">Subject</p><p style="color:var(--muted);margin:6px 0 0">No property selected. Search above, click a property on the map, or paste a listing on the right.</p>'; return; }
  const l=subject; const r=D().analyze(l); const c=r? D().CAT[r.cat] : null;
  box.innerHTML=`<p class="eyebrow">Subject</p><div style="display:flex;gap:12px;align-items:flex-start;margin-top:6px">${r? D().ring(r.score, r.cat) : ''}<div style="flex:1"><div style="font-family:var(--display);font-size:19px;font-weight:600">${X.esc(l.addr)}</div><div style="font-size:13px;color:var(--muted)">${X.esc(l.city)}${l.zip?' '+l.zip:''} · ${X.esc(l.county||'')}${l.county?' County':''} · ${X.esc(l.kind)}${l.approx?' · location approximate':''}</div><div style="font-size:13px;margin-top:4px">${X.fmt$(X.price(l))}${l.beds!=null?' · '+l.beds+' bd '+l.baths+' ba':''}${l.sqft?' · '+X.fmtN(l.sqft)+' sf':''}${l.lot?' · lot '+X.fmtN(l.lot)+' sf':''}${l.year?' · built '+l.year:''}${(l.units||1)>1?' · '+l.units+' units':''}</div>${c?`<div style="margin-top:6px;font-size:12px"><span class="badge" style="background:var(${c.c});color:#fff">${c.name}</span></div>`:''}</div></div>
  <div class="toolbar" style="margin:10px 0 0"><button class="btn primary" id="runbtn" ${running?'disabled':''}>${running?'Working…':'Run research agents'}</button><button class="btn" id="stopbtn" ${running?'':'disabled'}>Stop</button>${l.src!=='imp'&&L().allListings().includes(l)?'':''}<button class="btn" id="mapbtn">Open on map</button>${!X.allListings().includes(l)?'<button class="btn" id="savebtn">Save to my deals</button>':''}</div>`;
  $('#runbtn').addEventListener('click', run); $('#stopbtn').addEventListener('click', ()=>{ if(ctl) ctl.abort(); running=false; renderSubject(); });
  $('#mapbtn').addEventListener('click', ()=>{ if(!X.allListings().includes(l)) saveSubject(); X.select(l.id, true); });
  const sb=$('#savebtn'); if(sb) sb.addEventListener('click', ()=>{ saveSubject(); renderSubject(); X.toast('Saved to your deals'); });
}
function saveSubject(){ const X=L(); if(X.allListings().includes(subject)) return; X.state.imported.push(subject); X.store('imported', X.state.imported); X.fillCounties(); X.refresh(); }

/* ---------- search ---------- */
const rq=$('#rq'), rr=$('#rresults');
rq.addEventListener('input', ()=>{ const q=rq.value.trim().toLowerCase(); if(!q){ rr.classList.remove('on'); return; } const X=L(); const hits=X.allListings().filter(l=>`${l.addr} ${l.city} ${l.zip} ${l.nb||''} ${l.anb||''}`.toLowerCase().includes(q)).slice(0,8);
  rr.innerHTML=hits.map(l=>`<div data-id="${l.id}"><span>${X.esc(l.addr)}, ${X.esc(l.city)} ${l.zip||''}</span><span>${X.fmt$(X.price(l))}</span></div>`).join('')+(/\d/.test(q)? `<div class="new" data-new="1"><span>Create a new subject from “${X.esc(rq.value.trim())}”</span><span>↵</span></div>`:'');
  rr.classList.add('on'); $$('div[data-id]', rr).forEach(d=>d.addEventListener('click', ()=>{ subjectFrom(X.allListings().find(l=>l.id===d.dataset.id)); rr.classList.remove('on'); rq.value=''; })); const nw=$('div[data-new]', rr); if(nw) nw.addEventListener('click', ()=>{ newFromAddress(rq.value.trim()); rr.classList.remove('on'); }); });
rq.addEventListener('keydown', e=>{ if(e.key==='Enter'){ const first=$('div[data-id]', rr); if(first) first.click(); else if(rq.value.trim()) { newFromAddress(rq.value.trim()); rr.classList.remove('on'); } } if(e.key==='Escape') rr.classList.remove('on'); });
document.addEventListener('click', e=>{ if(!e.target.closest('.rsearch')) rr.classList.remove('on'); });
function parseAddress(s){ const X=L(); const zipM=s.match(/\b(9[45]\d{3})\b/); const zip=zipM?zipM[1]:''; let city=''; const parts=s.split(',').map(x=>x.trim()).filter(Boolean); const cities=Object.keys(X.M.cities); for(const p of parts.slice(1)){ const name=p.replace(/\b(CA|California)\b/i,'').replace(/\d{5}(-\d{4})?/,'').trim(); const hit=cities.find(c=>c.toLowerCase()===name.toLowerCase()); if(hit){ city=hit; break; } } if(!city && zip && X.M.zips[zip]) city=X.M.zips[zip].city||''; if(!city){ const lower=s.toLowerCase(); const hit=cities.filter(c=>lower.includes(c.toLowerCase())).sort((a,b)=>b.length-a.length)[0]; if(hit) city=hit; } const addr=(parts[0]||s).replace(/\d{5}(-\d{4})?/,'').trim(); return {addr, city, zip}; }
function newFromAddress(s){ const p=parseAddress(s); $('#s_addr').value=p.addr; $('#s_city').value=p.city; $('#s_zip').value=p.zip; $('#s_price').focus(); L().toast(p.zip||p.city? 'Fill in the price, then Create subject' : 'Add a city or ZIP so the market data can attach'); $('#subjform').scrollIntoView({behavior:'smooth', block:'center'}); }

/* ---------- extraction ---------- */
function regexExtract(t){ const g=(re,i=1)=>{ const m=t.match(re); return m? m[i].replace(/,/g,'') : ''; };
  const price=g(/\$\s?([\d,]{6,})/); const beds=g(/(\d+(?:\.\d)?)\s*(?:bd|bds|bed|beds|br|bedrooms?)\b/i); const baths=g(/(\d+(?:\.\d)?)\s*(?:ba|bath|baths|bathrooms?)\b/i); const sqft=g(/([\d,]{3,})\s*(?:sq\.? ?ft|sqft|sf)\b(?!.*lot)/i);
  let lot=g(/lot[^\d\n]{0,25}([\d,.]+)\s*(?:sq\.? ?ft|sqft|sf)/i); const acres=g(/([\d.]+)\s*acres?/i); if(!lot && acres) lot=String(Math.round(+acres*43560));
  const year=g(/(?:built|year built|constructed)[^\d\n]{0,12}((?:18|19|20)\d{2})/i); const units=g(/(\d+)\s*(?:units?|plex|-unit)/i); const zip=g(/\b(9[45]\d{3})\b/);
  const addrLine=(t.split('\n').map(x=>x.trim()).find(x=>/^\d+\s+[A-Za-z0-9.' -]+(St|Ave|Blvd|Dr|Rd|Ct|Ln|Pl|Way|Ter|Cir|Hwy|Street|Avenue|Boulevard|Drive|Road|Court|Lane|Place)\b/i.test(x))||'');
  const p=parseAddress(addrLine||t.slice(0,200)); return {addr:p.addr||addrLine, city:p.city, zip:zip||p.zip, price, beds, baths, sqft, lot, year, units, rent:g(/rent(?:al)?[^\d\n]{0,20}\$?\s?([\d,]{4,})\s*(?:\/|per)?\s*(?:mo|month)/i)}; }
function fillForm(f){ const set=(id,v)=>{ if(v!=null && v!=='') $('#'+id).value=v; }; set('s_addr',f.addr); set('s_city',f.city); set('s_zip',f.zip); set('s_price',f.price); set('s_beds',f.beds); set('s_baths',f.baths); set('s_sqft',f.sqft); set('s_lot',f.lot); set('s_year',f.year); set('s_units',f.units); set('s_rent',f.rent); if(f.kind) $('#s_kind').value=f.kind; }
$('#rextract').addEventListener('click', ()=>{ const t=$('#rpaste').value.trim(); if(!t) return; let f=null; try{ const o=JSON.parse(t); const list=L().importText(t,'pasted').listings; if(list.length){ subjectFrom(list[0]); $('#rextnote').textContent='Parsed as JSON — subject created.'; return; } }catch(e){} f=regexExtract(t); fillForm(f); $('#rextnote').textContent=Object.values(f).filter(Boolean).length+' fields found — check them, then Create subject.'; });
$('#rai').addEventListener('click', async()=>{ const s=await getSample(); const t=$('#rpaste').value.trim(); if(!s||!t) return; $('#rextnote').textContent='Asking Claude…'; try{ const f=await s.json('Extract real-estate listing fields from the text below. Reply with only a JSON object with keys: addr (street address without city), city, zip, price (number, USD), beds (number), baths (number), sqft (living area number), lot (lot sq ft number), year (year built), units (number of dwelling units), rent (monthly rent if stated), kind (one of "Single-family","Condominium","2 units","3 units","4 units","5+ units","Townhouse"). Use null for unknown. Example: {"addr":"123 Main St","city":"Oakland","zip":"94610","price":1200000,"beds":3,"baths":2,"sqft":1650,"lot":4000,"year":1925,"units":1,"rent":null,"kind":"Single-family"}\n\nTEXT:\n'+t.slice(0,8000), {modelTier:'quick'}); fillForm(f); $('#rextnote').textContent='Claude filled the form — check it, then Create subject.'; }catch(e){ $('#rextnote').textContent= e.code==='not_granted'? 'Claude not allowed for this page — using the built-in extractor.' : 'Claude could not parse it — using the built-in extractor.'; fillForm(regexExtract(t)); } });
$('#rmake').addEventListener('click', ()=>{ const X=L(); const v=id=>$('#'+id).value.trim(); if(!v('s_addr')||!v('s_price')){ X.toast('Address and price are required'); return; } const kind=v('s_kind'); const units=+v('s_units')|| (kind.match(/^(\d)/)? +kind.match(/^(\d)/)[1] : (kind==='5+ units'?5:1));
  const l=X.mk({addr:v('s_addr'), city:v('s_city'), zip:v('s_zip'), price:v('s_price'), beds:v('s_beds'), baths:v('s_baths'), sqft:v('s_sqft'), lot:v('s_lot'), year:v('s_year'), units, rent:v('s_rent'), kind}, 'research subject'); l.kind=kind==='5+ units'?'Small apartment (5+ units)':kind;
  if(l.lat==null){ X.toast('No coordinates and no known ZIP — add a Bay Area ZIP'); return; } subjectFrom(l); $('#subject').scrollIntoView({behavior:'smooth', block:'start'}); });

/* ---------- agents ---------- */
const AGENTS=[
  {id:'market', name:'Market agent', desc:'ZIP and city value/rent trends, yield rank', run: agentMarket},
  {id:'cash', name:'Cash-flow agent', desc:'Locator X score, break-even levers, rate sensitivity', run: agentCash},
  {id:'comps', name:'Comps agent', desc:'Similar recent sales from the public record', run: agentComps},
  {id:'reg', name:'Regulation & risk agent', desc:'Rent control, transfer tax, seismic, Prop 13', run: agentReg},
  {id:'value', name:'Value-add agent', desc:'ADU, SB 9, unit count, renovation reset', run: agentValue},
  {id:'exit', name:'Exit agent', desc:'Five-year hold, sale costs, 1031, IRR', run: agentExit},
  {id:'ai', name:'Claude deep-dive', desc:'Narrative report, questions for the seller, negotiation stance', run: agentAI, ai:true}
];
function renderAgents(){ const box=$('#agents'); if(!box) return; if(!subject){ box.innerHTML=''; return; } box.innerHTML=AGENTS.map(a=>{ const r=results[a.id]; const st=r? (r.error?'error':'done') : (running&&running===a.id?'run':'idle'); const off=a.ai && sampleFn===null; return `<div class="agent ${st==='run'?'run':st==='done'?'done':''} ${off?'off':''}" id="ag_${a.id}"><div class="ic">${st==='run'?'<span class="spin"></span>':st==='done'?'✓':st==='error'?'!':'·'}</div><b>${a.name}</b><span class="st">${off?'unavailable here':st==='run'?'working':st==='done'?'done':st==='error'?'failed':'queued'}</span><div class="sum">${off? 'Runs when this page is opened inside claude.ai and you allow it to ask Claude.' : (r? (r.error||r.summary) : a.desc)}</div></div>`; }).join(''); }
async function run(){ if(!subject||running) return; results={}; $('#report').innerHTML=''; ctl=new AbortController(); for(const a of AGENTS){ if(ctl.signal.aborted) break; running=a.id; renderSubject(); renderAgents(); try{ if(a.ai){ const s=await getSample(); if(!s){ results[a.id]={skipped:true, summary:'Not available in this host.'}; continue; } } await sleep(350); results[a.id]=await a.run(subject, ctl.signal); }catch(e){ results[a.id]={error: e && e.code? aiErr(e) : ('Failed: '+(e&&e.message||e)), findings:[]}; } renderAgents(); renderReport(); } running=false; renderSubject(); renderAgents(); renderReport(true); }
function aiErr(e){ switch(e.code){ case 'not_granted': return 'You have not allowed this page to ask Claude — the rest of the report stands on its own.'; case 'cancelled': return 'Stopped.'; case 'rate_limited': return 'Claude is busy or your usage limit is reached — try again later.'; case 'refused': return 'Claude declined this request.'; default: return 'Claude could not complete the deep-dive ('+e.code+').'; } }
const F=(k,v,n,level)=>({k,v,n,level});
function agentMarket(l){ const X=L(); const mk=X.marketFor(l); const z=X.M.zips[l.zip]; const c=X.M.cities[l.city]; const f=[];
  const zipsY=Object.entries(X.M.zips).map(([k,o])=>({k, y: X.last(o.v)&&X.last(o.r)? X.last(o.r)*12/X.last(o.v)*100 : null})).filter(x=>x.y).sort((a,b)=>b.y-a.y); const rank= mk.zhvi&&mk.zori? zipsY.findIndex(x=>x.k===l.zip)+1 : 0; const y = mk.zhvi&&mk.zori? mk.zori*12/mk.zhvi*100 : null;
  if(mk.zhvi) f.push(F('Typical home value ('+mk.src+')', X.fmt$(mk.zhvi), mk.yoy!=null? (mk.yoy>0?'up ':'down ')+Math.abs(mk.yoy).toFixed(1)+'% over 12 months' : '', mk.yoy>0?'good':mk.yoy<-2?'bad':'warn'));
  if(mk.zori) f.push(F('Typical rent ('+mk.src+')', '$'+X.fmtN(mk.zori)+'/mo', z&&z.r&&X.last(z.r)&&X.at(z.r,z.r.length-13)? 'rent '+((X.last(z.r)/X.at(z.r,z.r.length-13)-1)*100).toFixed(1)+'% y/y' : ''));
  if(y) f.push(F('Gross yield of the ZIP', y.toFixed(2)+'%', rank? `ranks #${rank} of ${zipsY.length} Bay Area ZIPs with rent data (median ${X.median(zipsY.map(x=>x.y)).toFixed(2)}%)` : '', y>=5.5?'good':y>=4.2?'warn':'bad'));
  if(c&&X.last(c.v)) f.push(F(l.city+' typical value', X.fmt$(X.last(c.v)), c.v&&X.at(c.v,c.v.length-13)? ((X.last(c.v)/X.at(c.v,c.v.length-13)-1)*100).toFixed(1)+'% y/y' : ''));
  if(mk.nbv) f.push(F((l.nb||'Neighborhood')+' typical value', X.fmt$(X.last(mk.nbv)), mk.nbv.length>=13&&mk.nbv[0]? ((X.last(mk.nbv)/mk.nbv[0]-1)*100).toFixed(1)+'% over 12 months':''));
  const P=X.price(l); if(mk.zhvi&&P) f.push(F('Subject price vs ZIP typical value', (P/mk.zhvi*100).toFixed(0)+'%', P>mk.zhvi*1.5? 'well above the typical home — expect a thinner buyer pool on exit' : P<mk.zhvi*0.8? 'below the typical home — entry-level for the ZIP' : 'in line with the ZIP'));
  const trend24 = z&&z.v&&z.v[0]&&X.last(z.v)? (X.last(z.v)/z.v[0]-1)*100 : null; if(trend24!=null) f.push(F('Two-year ZIP value change', (trend24>0?'+':'')+trend24.toFixed(1)+'%', 'Zillow ZHVI, '+X.M.months[0].slice(0,7)+' → '+X.M.months[X.M.months.length-1].slice(0,7), trend24>0?'good':'bad'));
  return {summary: mk.zhvi? `ZIP ${l.zip||'—'} typical value ${X.fmt$(mk.zhvi)} (${mk.yoy!=null?(mk.yoy>0?'+':'')+mk.yoy.toFixed(1)+'% y/y':'no trend'}), rent $${X.fmtN(mk.zori)}/mo, gross yield ${y?y.toFixed(1)+'%':'—'}${rank?` (#${rank} of ${zipsY.length})`:''}.` : 'No Zillow market data for this ZIP or city.', findings:f, spark: z&&z.v? '<div class="sparkwrap"><div style="font-size:11px;color:var(--muted)">ZIP '+l.zip+' typical value, last 25 months</div>'+X.spark(z.v)+'</div>':''}; }
function agentCash(l){ const X=L(); const r=D().analyze(l); const d=r.d, a=X.state.assump; const f=[
  F('Locator X score', r.score+' / 100', D().CAT[r.cat].name, r.score>=60?'good':r.score>=40?'warn':'bad'),
  F('Estimated rent', '$'+X.fmtN(d.rentMo)+'/mo', d.rentHow),
  F('Net operating income', X.fmtFull(d.noi), `cap rate ${X.fmtPct(d.cap)} · gross yield ${X.fmtPct(d.gross)}`, d.cap>=5.5?'good':d.cap>=4?'warn':'bad'),
  F('Cash flow after mortgage', (d.cfMo>0?'+':'')+X.fmt$(d.cfMo)+'/mo', `${a.down}% down at ${a.rate}% · DSCR ${d.dscr?d.dscr.toFixed(2):'—'} · cash-on-cash ${X.fmtPct(d.coc)}`, d.cf>0?'good':d.dscr>=0.85?'warn':'bad'),
  F('Cash to close', X.fmtFull(d.cash), `${a.down}% down + ${a.closing}% costs`)
]; r.levers.forEach(x=>f.push(F(x[0], x[1], '')));
  const rates=[a.rate-1, a.rate-0.5, a.rate, a.rate+0.5, a.rate+1]; const downs=[10,20,25,30,40,50]; const n=a.term*12; const rows=downs.map(dn=>{ const loan=d.P*(1-dn/100); return {dn, cells: rates.map(rt=>{ const m=rt/100/12; const pay=loan*m/(1-Math.pow(1+m,-n))*12; return (d.noi-pay)/12; })}; });
  const sens=`<table class="sens"><tr><th>Down ↓ / Rate →</th>${rates.map(r=>`<th>${r.toFixed(2)}%</th>`).join('')}</tr>${rows.map(r=>`<tr><td>${r.dn}%</td>${r.cells.map(c=>`<td class="${c>0?'pos':'neg'}">${(c>0?'+':'')+X.fmt$(c)}</td>`).join('')}</tr>`).join('')}</table><div style="font-size:11px;color:var(--muted);margin-top:4px">Monthly cash flow by down payment and rate, at the current rent estimate.</div>`;
  return {summary: `${D().CAT[r.cat].name} — score ${r.score}. ${r.rec}`, findings:f, html:sens, analysis:r}; }
function agentComps(l){ const X=L(); const P=X.price(l); const km=(a,b)=>{ const R=6371, dLat=(b.lat-a.lat)*Math.PI/180, dLng=(b.lng-a.lng)*Math.PI/180; const s=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLng/2)**2; return 2*R*Math.asin(Math.sqrt(s)); };
  const multi=(l.units||1)>1; const pool=X.allListings().filter(x=>x!==l && x.id!==l.id && x.lat!=null).map(x=>({x, d:km(l,x)})).filter(o=>o.d<=3 && ((o.x.units||1)>1)===multi).sort((a,b)=>a.d-b.d).slice(0,8);
  const f=[]; if(!pool.length) return {summary:'No comparable public-record sales within 3 km in this dataset — import recent sales or MLS solds for this area.', findings:[F('Comparable sales found','0','within 3 km, same unit type')]};
  const pps=pool.filter(o=>o.x.sqft).map(o=>X.price(o.x)/o.x.sqft); const medP=X.median(pool.map(o=>X.price(o.x))); const medPps=pps.length? X.median(pps):null;
  f.push(F('Comparable sales', String(pool.length), `within ${pool[pool.length-1].d.toFixed(1)} km · median ${X.fmt$(medP)} · ${medPps?'$'+X.fmtN(medPps)+'/sf':'no area data'}`));
  if(medPps && l.sqft){ const sub=P/l.sqft; f.push(F('Subject $/sf vs comps', '$'+X.fmtN(sub)+' vs $'+X.fmtN(medPps), sub>medPps*1.15? 'priced above comparable sales — negotiate or justify with condition' : sub<medPps*0.85? 'priced below comparable sales — verify condition and tenancy' : 'in line with recent sales', sub>medPps*1.15?'bad':sub<medPps*0.85?'good':'warn')); f.push(F('Indicated value at comp $/sf', X.fmt$(medPps*l.sqft), 'median comp $/sf × subject area')); }
  pool.slice(0,6).forEach(o=>f.push(F(o.x.addr+', '+o.x.city, X.fmt$(X.price(o.x)), `${o.d.toFixed(1)} km · ${o.x.kind}${o.x.sqft?' · '+X.fmtN(o.x.sqft)+' sf · $'+X.fmtN(X.price(o.x)/o.x.sqft)+'/sf':''} · ${o.x.priceDate||''}`)));
  return {summary:`${pool.length} comparable ${multi?'multi-unit':'single-unit'} sales within 3 km, median ${X.fmt$(medP)}${medPps?' and $'+X.fmtN(medPps)+'/sf':''}${medPps&&l.sqft?`; subject at $${X.fmtN(P/l.sqft)}/sf`:''}.`, findings:f}; }
function transferTax(P, city, county){ const c=(city||'').toLowerCase(); let local=0, note=''; if(c==='san francisco'){ const r = P<=250000?0.5: P<=999999?0.68 : P<=4999999?0.75 : P<=9999999?2.25 : P<=24999999?5.5 : 6; local=P*r/100; note=`SF transfer tax ${r}%`; } else if(c==='oakland'){ const r = P<=300000?1 : P<=2000000?1.5 : P<=5000000?1.75 : 2.5; local=P*r/100+P*0.0011; note=`Oakland ${r}% + county $1.10/1k`; } else if(c==='berkeley'){ local=P*0.015+P*0.0011; note='Berkeley 1.5% + county $1.10/1k'; } else if(c==='alameda'){ local=P/1000*12+P*0.0011; note='Alameda city $12/1k + county $1.10/1k'; } else if(c==='piedmont'){ local=P/1000*13+P*0.0011; note='Piedmont $13/1k + county'; } else if(c==='emeryville'){ local=P*0.012+P*0.0011; note='Emeryville 1.2% + county'; } else if(c==='san leandro'){ local=P/1000*11+P*0.0011; note='San Leandro $11/1k + county'; } else if(c==='hayward'){ local=P/1000*8.5+P*0.0011; note='Hayward $8.50/1k + county'; } else if(c==='san jose'){ local=P*0.0011 + (P>2000000? P*(P<=5000000?0.0075:P<=10000000?0.01:0.015) : 0)+P/1000*3.3; note='San Jose $3.30/1k + Measure E above $2M + county'; } else { local=P*0.0011; note='County documentary transfer tax $1.10 per $1,000 (city may add its own)'; } return {amt:local, note}; }
function agentReg(l){ const X=L(); const rc=D().rentControl(l); const P=X.price(l); const tt=transferTax(P, l.city, l.county); const multi=(l.units||1)>1; const f=[
  F('Rent regulation', rc.reg, multi? 'applies to existing tenancies; verify current rents and any buyout/relocation exposure' : 'owner-occupied single-family and condos are exempt from AB 1482 when the notice is given', rc.level),
  F('Property tax reset (Prop 13)', X.fmtFull(P*X.taxRate(l)/100)+'/yr', `${X.taxRate(l)}% of your purchase price; rises at most 2%/yr after — the seller's bill was likely far lower`),
  F('Transfer tax at closing', X.fmtFull(tt.amt), tt.note, tt.amt>P*0.01?'warn':'good'),
  F('Seismic', l.year&&l.year<1978&&multi? 'Soft-story retrofit likely required' : l.year&&l.year<1980? 'Pre-1980 — check foundation, bolting, cripple walls' : 'Check the state seismic hazard map', 'Mandatory soft-story ordinances: SF (5+ units), Oakland, Berkeley; liquefaction zones ring the Bay shoreline and fill areas', l.year&&l.year<1978&&multi?'bad':'warn'),
  F('Insurance', X.fmtFull(P*X.state.assump.ins/100)+'/yr assumed', 'California homeowner insurance has tightened; get a quote before removing contingencies — wildfire-interface and older electrical raise it')
]; if(/condo/i.test(l.kind||'')) f.push(F('HOA', 'assumed $'+X.fmtN(X.state.assump.hoa===''?450:X.state.assump.hoa)+'/mo', 'read the reserve study, litigation disclosures and rental caps before you rely on rent', 'warn'));
  if((l.city||'').toLowerCase()==='san francisco' && multi) f.push(F('Condo conversion', 'Effectively closed', 'SF suspended the lottery for buildings of 3+ units; 2-unit owner-occupied bypass has conditions', 'warn'));
  return {summary:`${rc.reg}. Transfer tax ≈ ${X.fmtFull(tt.amt)}; first-year property tax ≈ ${X.fmtFull(P*X.taxRate(l)/100)}.`, findings:f}; }
function agentValue(l){ const X=L(); const va=D().valueAdd(l); const mk=X.marketFor(l); const f=[]; const adu=(mk.zori||3000)*0.85;
  if(l.lot && !/condo/i.test(l.kind||'')){ const ok=l.lot>=2500; f.push(F('ADU by right', ok?'Likely':'Tight lot', ok? `state law (Gov. Code 66310 et seq.) requires ministerial approval of an ADU up to 800–1,200 sf; a $250k build renting at ~$${X.fmtN(adu)}/mo is a ${(adu*12/250000*100).toFixed(0)}% yield on the addition` : 'a junior ADU or garage conversion may still fit', ok?'good':'warn'));
    if(l.lot>=2400) f.push(F('SB 9 lot split', l.lot>=4000?'Possible':'Marginal', 'urban lot split into two parcels of ≥1,200 sf each, up to two units per lot; owner-occupancy affidavit required', l.lot>=4000?'good':'warn')); }
  if((l.units||1)>1) f.push(F('Rent reset on turnover', 'Available', `${l.units} units; each vacancy re-sets to market — compare current rents to the ZIP's $${X.fmtN(mk.zori||0)}/mo`, 'good'));
  if(l.year && l.year<1960) f.push(F('Renovation reset', 'Strong', `built ${l.year}; a cosmetic turn typically lifts rent 10–20% and value with it`, 'good'));
  if(l.rooms && l.beds && l.rooms-l.beds>=5) f.push(F('Add a bedroom', 'Room count suggests it', `${l.rooms} rooms, ${l.beds} bedrooms on the assessor's record`, 'good'));
  if(!f.length) f.push(F('Value-add signal', 'Weak', 'condo or small lot with no obvious lever — the return must come from price', 'warn'));
  const dev=window.LXDev? window.LXDev.assess(l) : null;
  if(dev){ dev.list.filter(o=>o.feas!=='no'&&o.capex>0).slice(0,4).forEach(o=>f.push(F(o.name, X.fmt$(o.capex)+' → '+(o.profit>0?'+':'')+X.fmt$(o.profit), o.basis+(o.addRent? ' · adds $'+X.fmtN(o.addRent)+'/mo':'')+' · ~'+o.months+' mo', o.profit>0?'good':'warn'))); }
  return {summary:`Value-add score ${va.score}/100. ${dev&&dev.best? dev.summary : (va.items[0]||'No strong lever.')} Full economics on the Underwrite tab.`, findings:f}; }
function agentExit(l){ const X=L(); const r=D().analyze(l); const d=r.d, a=X.state.assump; const P5=d.proj[4]; const saleCost=P5.value*0.06; const loanBal=P5.value-P5.equity; const net=P5.value-saleCost-loanBal; const invested=d.cash; const cfSum=d.proj.reduce((s,p)=>s+p.cf,0); const totalReturn=net+cfSum-invested;
  // IRR via bisection on cash flows: -invested, cf1..cf4, cf5+net
  const flows=[-invested, ...d.proj.slice(0,4).map(p=>p.cf), d.proj[4].cf+net]; const npv=r0=>flows.reduce((s,c,i)=>s+c/Math.pow(1+r0,i),0); let lo=-0.9, hi=1, irr=null; if(npv(lo)>0 && npv(hi)<0){ for(let i=0;i<60;i++){ const mid=(lo+hi)/2; if(npv(mid)>0) lo=mid; else hi=mid; } irr=lo; }
  const f=[F('Year-5 value at '+d.appr.toFixed(1)+'%/yr', X.fmt$(P5.value), 'appreciation defaults to the ZIP\'s last-12-month change; edit it in the map drawer'), F('Equity at year 5', X.fmt$(P5.equity), `after ${X.fmt$(loanBal)} loan balance`), F('Net sale proceeds', X.fmt$(net), '6% selling costs, loan paid off'), F('Cumulative cash flow (5 yrs)', X.fmtFull(cfSum), cfSum>0?'':'the amount you feed it over the hold', cfSum>0?'good':'bad'), F('Total 5-year return on cash', (totalReturn>0?'+':'')+X.fmt$(totalReturn), `on ${X.fmt$(invested)} invested · IRR ${irr!=null? (irr*100).toFixed(1)+'%' : '—'}`, totalReturn>0?'good':'bad'), F('Break-even appreciation', (()=>{ let lo=-0.2, hi=0.3; for(let i=0;i<50;i++){ const mid=(lo+hi)/2; let v=d.P; for(let y=0;y<5;y++) v*=1+mid; const netm=v*0.94-loanBal; if(netm+cfSum-invested>0) hi=mid; else lo=mid; } return (hi*100).toFixed(1)+'%/yr'; })(), 'the appreciation rate at which a five-year hold returns your cash'), F('1031 exchange', 'Defers the gain', 'identify a replacement within 45 days, close within 180 — the Bay Area equity becomes cash-flow elsewhere')];
  return {summary:`Five-year hold returns ${(totalReturn>0?'+':'')+X.fmt$(totalReturn)} on ${X.fmt$(invested)} (IRR ${irr!=null?(irr*100).toFixed(1)+'%':'—'}) at ${d.appr.toFixed(1)}% appreciation.`, findings:f}; }
async function agentAI(l, signal){ const X=L(); const s=await getSample(); const brief={subject:{address:l.addr, city:l.city, zip:l.zip, county:l.county, type:l.kind, units:l.units, beds:l.beds, baths:l.baths, sqft:l.sqft, lot:l.lot, year:l.year, price:X.price(l), zoning:l.zoning, source:l.src==='imp'?'user data':'county assessor record (price = post-sale assessed value)'}, assumptions:X.state.assump, findings:Object.fromEntries(Object.entries(results).filter(([k,v])=>v&&v.findings).map(([k,v])=>[k,{summary:v.summary, items:v.findings.map(f=>[f.k,f.v,f.n].filter(Boolean).join(' — '))}]))};
  const prompt=`You are the deep-dive research agent inside locator.x, a Bay Area real-estate investor tool built on a cash-flow-first doctrine (assets pay you, cash flow before capital gains, good debt versus bad debt, verify before you trust). Write a rigorous, plain-English research memo for the property below using ONLY the data provided plus general knowledge of the SF Bay Area market and California law. Do not invent specific facts about this address; where something must be verified, say so.\n\nFormat: plain text, 350-500 words, with these short headers on their own lines: VERDICT (2-3 sentences in Locator X terms — asset or liability, and why), WHAT THE NUMBERS SAY, WHAT TO VERIFY BEFORE OFFERING (5 concrete items), QUESTIONS FOR THE SELLER OR AGENT (5), RED FLAGS FOR THIS CITY AND BUILDING AGE, NEGOTIATION STANCE (a target price or terms that would make it cash-flow, with the arithmetic). No markdown symbols, no bullets — use short lines.\n\nDATA:\n${JSON.stringify(brief)}`;
  const el=()=>$('#ai_out'); let text=''; const res=await s(prompt, {signal, onText:({text:t})=>{ text=t; const o=el(); if(o) o.textContent=t; }}); return {summary:'Memo written — see the report below.', findings:[], ai:res.text, truncated:res.truncated}; }

/* ---------- report ---------- */
function renderReport(final){ const X=L(); if(!subject) return; const l=subject; const r=D().analyze(l); const c=D().CAT[r.cat]; const box=$('#report');
  const sec=(a)=>{ const res=results[a.id]; if(!res) return ''; if(res.skipped) return ''; if(res.error) return `<h3>${a.name}</h3><p style="font-size:13px;color:var(--muted)">${X.esc(res.error)}</p>`; if(a.ai) return `<h3>${a.name}</h3><div class="ai" id="ai_out">${X.esc(res.ai||'')}</div>${res.truncated?'<p style="font-size:12px;color:var(--warn)">Cut short by the length limit.</p>':''}`; return `<h3>${a.name}</h3><p style="font-size:13px;margin:0 0 8px">${X.esc(res.summary)}</p><div class="findings">${res.findings.map(f=>`<div class="f ${f.level||''}"><span>${X.esc(f.k)}</span><span class="v">${X.esc(f.v)}</span>${f.n?`<span class="n">${X.esc(f.n)}</span>`:''}</div>`).join('')}</div>${res.html||''}${res.spark||''}`; };
  const aiRunning = running==='ai'; const aiBlock = aiRunning? `<h3>Claude deep-dive</h3><div class="ai" id="ai_out">Thinking…</div>` : '';
  box.innerHTML=`<div class="report"><div class="rh">${D().ring(r.score, r.cat, 84, true)}<div style="flex:1;min-width:240px"><div class="eyebrow">Research report · ${new Date().toISOString().slice(0,10)} · locator.x</div><h2>${X.esc(l.addr)}, ${X.esc(l.city)}</h2><div style="font-size:13px;color:var(--muted)">${X.fmt$(X.price(l))} · ${X.esc(l.kind)} · <span style="color:var(${c.c});font-weight:600">${c.name}</span> · score ${r.score}/100</div><p style="font-size:14px;margin:8px 0 0;max-width:70ch">${X.esc(r.rec)}</p></div><div style="display:flex;flex-direction:column;gap:6px"><button class="btn" id="copyrep">Copy report (Markdown)</button>${!X.allListings().includes(l)?'<button class="btn" id="saverep">Save to my deals</button>':''}<button class="btn" id="dashrep">Open in dashboard</button></div></div>${AGENTS.filter(a=>!a.ai).map(sec).join('')}${aiBlock || sec(AGENTS[6])}<p class="disclaimer">Generated from public records (county assessor rolls), Zillow Research indexes and your assumptions. Rent is an index-based estimate, not a survey of this property. Not legal, tax or investment advice.</p></div>`;
  $('#copyrep').addEventListener('click', async()=>{ const md=toMarkdown(l,r); try{ await navigator.clipboard.writeText(md); X.toast('Report copied'); }catch(e){ const ta=document.createElement('textarea'); ta.value=md; document.body.appendChild(ta); ta.select(); document.execCommand('copy'); ta.remove(); X.toast('Report copied'); } });
  const sv=$('#saverep'); if(sv) sv.addEventListener('click', ()=>{ saveSubject(); renderSubject(); renderReport(true); X.toast('Saved to your deals'); });
  $('#dashrep').addEventListener('click', ()=>{ if(!X.allListings().includes(l)) saveSubject(); X.showView('dash'); D().render(); D().focusOn(l.id); });
}
function toMarkdown(l,r){ const X=L(); let md=`# ${l.addr}, ${l.city} ${l.zip||''}\n\n**${D().CAT[r.cat].name}** · Locator X score ${r.score}/100 · ${X.fmt$(X.price(l))} · ${l.kind}\n\n${r.rec}\n\n`; AGENTS.forEach(a=>{ const res=results[a.id]; if(!res||res.skipped) return; md+=`## ${a.name}\n\n`; if(res.error){ md+=res.error+'\n\n'; return; } if(a.ai){ md+=(res.ai||'')+'\n\n'; return; } md+=res.summary+'\n\n'; res.findings.forEach(f=>{ md+=`- **${f.k}:** ${f.v}${f.n?' — '+f.n:''}\n`; }); md+='\n'; }); md+=`_Generated by locator.x (powered by AGI Corp) on ${new Date().toISOString().slice(0,10)} from public records, Zillow Research indexes and user assumptions. Not advice._\n`; return md; }

/* ---------- instant lookups ---------- */
function renderLinks(){ const box=$('#rlinks'); if(!box) return; const l=subject; if(!l){ box.innerHTML='<div style="font-size:12px;color:var(--muted)">Pick a subject to build its links.</div>'; return; } const q=encodeURIComponent(`${l.addr}, ${l.city}, CA ${l.zip||''}`.trim()); const city=(l.city||'').toLowerCase(); const ll=l.lat!=null? `${l.lat},${l.lng}`:'';
  const links=[['Zillow','listing, Zestimate, history',`https://www.zillow.com/homes/${q}_rb/`],['Redfin','sale history, comps',`https://www.google.com/search?q=site%3Aredfin.com+${q}`],['Realtor.com','listing & tax history',`https://www.google.com/search?q=site%3Arealtor.com+${q}`],['Google Maps','satellite & Street View', ll?`https://www.google.com/maps/search/?api=1&query=${ll}`:`https://www.google.com/maps/search/?api=1&query=${q}`],['Street View','curb appeal, neighbors', ll?`https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=${ll}`:`https://www.google.com/maps/search/?api=1&query=${q}`]];
  if(city==='san francisco'){ links.push(['SF Property Info Map','zoning, permits, complaints',`https://sfplanninggis.org/pim/?search=${encodeURIComponent(l.addr)}`],['SF Assessor','roll value, sale history','https://www.sfassessor.org/property-information/homeowners/homeowners-search'],['SF DBI permits','building permits','https://dbiweb02.sfgov.org/dbipts/default.aspx?page=AddressQuery'],['SF Rent Board','rent control lookup','https://www.sf.gov/departments/rent-board']); }
  else if(l.county==='Alameda'){ links.push(['Alameda County Assessor','parcel & value','https://www.acgov.org/assessor/'],['Alameda Parcel Viewer','GIS parcel record','https://www.acgov.org/assessor/parcelviewer.htm']); if(city==='oakland') links.push(['Oakland permits (Accela)','permits & code cases','https://aca-prod.accela.com/OAKLAND/'],['Oakland RAP','rent adjustment program','https://www.oaklandca.gov/topics/rent-adjustment-program']); if(city==='berkeley') links.push(['Berkeley Rent Board','registration & ceilings','https://rentboard.berkeleyca.gov/']); }
  else if(l.county==='Santa Clara') links.push(['SCC Assessor','parcel lookup','https://www.sccassessor.org/']); else if(l.county==='Contra Costa') links.push(['CCC Assessor','parcel & values','https://www.contracosta.ca.gov/191/Assessor']); else if(l.county==='San Mateo') links.push(['SMC Assessor','parcel & values','https://www.smcacre.org/']);
  links.push(['FEMA flood map','flood zone',`https://msc.fema.gov/portal/search?AddressQuery=${q}`],['CA seismic hazard zones','liquefaction & landslide','https://maps.conservation.ca.gov/cgs/EQZApp/app/'],['Walk Score','walk/transit/bike',`https://www.walkscore.com/score/${q}`],['GreatSchools','assigned schools',`https://www.greatschools.org/search/search.page?q=${l.zip||q}`],['Census Reporter','ZIP demographics', l.zip?`https://censusreporter.org/profiles/86000US${l.zip}-${l.zip}/`:'https://censusreporter.org/'],['HUD Fair Market Rent','rent floor by bedroom','https://www.huduser.gov/portal/datasets/fmr.html'],['Rentometer','rent comps','https://www.rentometer.com/'],['CrimeMapping','recent incidents',`https://www.crimemapping.com/map/location/${q}`],['Zillow Research','ZHVI / ZORI files','https://www.zillow.com/research/data/']);
  box.innerHTML=links.map(x=>`<a href="${x[2]}" target="_blank" rel="noopener">${x[0]}<small>${x[1]}</small></a>`).join(''); }

window.LXResearch={subjectFrom, show, run, get subject(){ return subject; }};
})();
