/* locator.x — Trade School track: The developer’s permission and professional stack.
   Original curriculum written for locator.x. This track teaches the permission stack as a
   PUBLIC RECORD — where each approval lives, who signs for what, which instruments protect
   whom, and how a practitioner verifies each one — and deliberately states no city’s fee,
   window, count or deadline: the learner finds each figure with the issuing authority and
   records it with the date. It confers no licence, degree, accreditation or credit. The
   D-pillar lessons carry the theory (the development system, feasibility, zoning); this
   track is the practitioner’s navigation beside them. Concatenated after tradeschool.js;
   registers itself into window.LXTS.TRACKS. */
(function(){
'use strict';

const TRACK={id:'developer', name:'The developer’s permission and professional stack', who:'Developers, owner-builders and the teams around them', c:'--cat1',
 blurb:'The permission stack read as a public record: where each approval lives and how to pull a parcel’s permit history before buying; the pre-application meeting and how to record what the city did not say; who signs for what; developer and owner-builder registration as three outcomes; bonds and guarantees as categories; fees, exactions and conditions as sourced lines; the lender’s draw machinery; inspections as gates; the public hearing and the record it rests on; and the dated permission notebook the track produces. You bring the figures; this track teaches where they live.',
 modules:[
  {id:'dp1', t:'The permission stack as a public record — where each approval lives, and pulling a parcel’s history before buying', body:`
   <p>Every approval a building needs is issued by a public body, and nearly every public body keeps a register of what it issued. That makes the permission stack a record you can read before you own anything. The stack has a recognisable order wherever you are. <b>Zoning verification</b> comes from the planning department: a letter or a portal entry stating the parcel’s district, the overlays on it, and whether the existing use is permitted, conditional or nonconforming. <b>Plan check</b> (plan review) is the building department’s reading of the drawings against the adopted codes, recorded as rounds of comments and responses. <b>The building permit</b> is the instrument that authorises the work; it names the scope, the parcel, the owner and the contractor, and it carries a number that every later entry hangs from. <b>Inspections</b> are logged against that number, each with a result. <b>The certificate of occupancy</b> (or certificate of completion, depending on the jurisdiction and the work) closes the stack and states what the building may be used for.</p>
   <p>Where these live differs by city: a single permit portal, separate planning and building portals, a counter that answers records requests, or a mixture. The probe is the same. Search by address <i>and</i> by parcel number, because addresses are renamed and parcels are split and merged, and a search by one alone misses history filed under the other. Read every permit the search returns, and read its <b>status word</b> — issued, finaled, expired, cancelled, withdrawn, suspended — in the portal’s own glossary, because the same word carries different weight in different cities.</p>
   <p>What you are looking for before buying is the gap between the record and the building. A permit with no final inspection is an open item. An expired permit is work whose compliance was never confirmed. Work visible on site with no permit at all is a larger gap, and its cost is not knowable from the record. Code-enforcement complaints and violations are usually a sibling register under the same department; read them alongside the permits. Write each permit as a row: number, scope, issuing department, status word, last inspection date, and whether anything remains open.</p>
   <p><b>What this app does with it.</b> The Permits &amp; code group in the record views is the door to each market’s permit register and its code-enforcement sibling; the Record Locker is where the dated copies of what you pulled belong, so that the permit history you relied on is retrievable with the date you read it. Confirm every status with the issuing building department and record the date beside each row.</p>
   <p class="src">Source to check: the planning department’s zoning verification page or letter process, the building department’s permit portal and its status glossary, and the code-enforcement register; search by address and by parcel number, and date every row.</p>`,
   drill:{q:'A parcel’s permit history shows a kitchen remodel permit with the status word “expired” and no final inspection logged. Under this module, what is it?', opts:['Closed: an expired permit is one the department stopped tracking, so the work stands as built','Evidence the remodel was never started, since a finished job would carry a final inspection','An open item: compliance was never confirmed, and resolution is the building department’s answer to give','A planning matter: once a permit expires it leaves the building register for the zoning file'], a:2, why:'Expiry is a status word about the permit, not a finding about the work, and it says nothing about whether the work was done. Without a final, the record never confirmed the work met code; what the department requires to resolve it is the department’s answer to give, recorded with the date.'}},

  {id:'dp2', t:'The pre-application meeting — what to bring, what to ask, and how to record what the city did not say', body:`
   <p>Most planning departments offer, and some require, a meeting before an application is filed. Its names vary — pre-application, pre-submittal, development review, concept review — and so does its shape: a single planner at a counter, or a table of planning, building, fire, public works and utility staff reading the same concept. Whether it is required, whether it is charged for, and who attends are the first facts to find on the department’s page.</p>
   <p>What to bring is a short list. The parcel’s zoning verification from the last module. A concept site plan that shows what you intend and nothing you do not yet know. A written list of questions, each tied to a code section you have read. The planner’s time is the scarce thing in the room; a question that cites the section it is about gets a better answer than one that asks what the rules are.</p>
   <p>What to ask falls into categories. <b>Which approval path</b> applies to this proposal and which body decides it. <b>Which studies</b> the application will require — traffic, environmental, geotechnical, drainage, historic, shadow, noise — because each is a line of cost and a span of time. <b>Which departments</b> review, and in what order. <b>The submittal checklist</b> for the application type. <b>The known issues</b> with the site that the planner can see from their own records and you cannot: overlays, pending code changes, prior applications, easements, flood designation, historic status.</p>
   <p>The record you keep matters more than the meeting. Pre-application comments are, in most cities, expressly non-binding; the department may say so on the form. So write who attended, each question as asked, the answer as given, and — separately — the questions that were deflected, deferred or not answered. Send the notes back to the planner and ask for corrections; silence is not agreement, and a reply that corrects nothing is still a dated reply. Where the city issues a written pre-application letter, that letter is the record and the notes are commentary on it. The gap between what the city said and what it did not say is the list of open items your feasibility work has to carry.</p>
   <p><b>What this app does with it.</b> The feasibility gate asks whether the questions that decide the project have answers; the unanswered column of your pre-application notes is that list, and the decision memo is where the answered ones are cited by letter and date. Confirm every pre-application comment with the department that made it, and record the date.</p>
   <p class="src">Source to check: the planning department’s pre-application page (whether required, what it costs, who attends, what to submit) and the department’s own statement on whether its comments bind; date the notes and the reply.</p>`,
   drill:{q:'At a pre-application meeting a planner says the concept “looks fine to me.” How does this track record that?', opts:['As the planner’s name, the words and the date, marked as binding nothing, then sent back for correction','As a preliminary approval, cited in the feasibility memo under the planner’s name and the meeting date','As grounds to skip the zoning verification letter, since the planner has read the parcel’s district already','Not at all: a spoken comment enters the file only when the department repeats it in a written letter'], a:0, why:'Pre-application comments are usually expressly non-binding, so the useful record is who said what, when, and that it is not an approval. Sending the notes back for correction makes the city’s reply, or its silence, a dated entry; where the city issues a written letter, that letter is the record and the notes are commentary on it.'}},

  {id:'dp3', t:'Who signs for what — stamps, seals, reports and the permit application, and the register that verifies each seat', body:`
   <p>The licensing track’s module on the developer’s professional stack covers which board licenses each seat and how to look a stamp up. This module is about the <b>documents</b> — what each seat signs, what that signature asserts, and how the signatures fit together in a permit set — because a developer verifies seats by matching the signature to the thing it is on.</p>
   <p>The <b>architect of record</b> seals the architectural sheets and, in most jurisdictions, is the coordinating professional whose name the permit application carries as designer. The <b>engineer of record</b> for each discipline — structural, civil, mechanical, electrical, plumbing, fire protection — seals the sheets of that discipline. Some elements are not designed by the engineer of record at all: trusses, pre-engineered systems, sprinkler layouts and similar items are <b>delegated design</b>, sealed by a specialty engineer retained by the supplier or subcontractor and then reviewed and accepted by the engineer of record, whose acceptance is itself a document. The <b>land surveyor</b> seals several distinct products — the boundary survey, the topographic survey, the plat, and the foundation-location or as-built survey the lender or the city asks for during construction — and each is a separate certification with its own date. The <b>geotechnical engineer</b> seals the soils report, which is not a formality: it is the stated basis for the foundation design, and the structural sheets cite it. The <b>Environmental Professional</b> signs the site assessment, verified as the licensing track describes.</p>
   <p>Two more signatures are easy to overlook. The <b>permit application</b> itself is signed by the licensed contractor or, where the owner is building, by the owner under an owner-builder declaration; the permit then names who is responsible for the work. And where the adopted code requires <b>special inspections</b> of certain structural or life-safety elements, a statement of special inspections is part of the permit set and names the agency the owner — not the contractor — retains to perform them. The pattern worth memorising: every signature answers the question <i>who is accountable for this sheet or this report</i>, and a sheet with no accountable name is the question to raise at plan check.</p>
   <p>Verification is a register, kept per project and dated: seat, name, licence or certification number, the regulator that issued it, the sheets or reports signed, the status on the date of signature, and the date you checked. Boards publish which professions may sign which kinds of documents, and building departments publish which they accept for which building types; where an architect’s and an engineer’s practice overlap, the department’s policy decides what it will accept. Confirm each seat’s authority to sign with the board that licenses it and with the building department that accepts the sheet, and record the date on the register.</p>
   <p class="src">Source to check: the state architecture, engineering and surveying boards’ pages on what each profession may seal; the building department’s submittal policy on accepted professionals; the statement of special inspections in the permit set. Date each register row.</p>`,
   drill:{q:'The roof trusses in a permit set are sealed by an engineer retained by the truss supplier, not by the project’s structural engineer of record. What is this, and what does verification look like?', opts:['An error in the set: only the engineer of record may seal a structural element, so the sheet is rejected','A surveying matter: trusses set the ridge height, so the surveyor’s as-built certification covers them','Acceptable once the general contractor countersigns, since the supplier works under its contract','Delegated design: the specialty seal and the engineer of record’s written acceptance are each verified'], a:3, why:'Delegated design is a normal pattern: a specialty engineer designs the component and the engineer of record reviews and accepts it. The developer’s register therefore carries two accountable names for the trusses, each checked against its board with a date, and the acceptance document is part of what is verified.'}},

  {id:'dp4', t:'Developer and owner-builder registration — three outcomes, and the probe that finds yours', body:`
   <p>The question <i>does the developer, as such, need to register with anyone?</i> has no single national answer, and a practitioner handles it the way the licensing track handles every such question: as a probe with a small set of possible outcomes. Three cover the ground. <b>Registration required</b>: some states register builders of new residences, some register developers or declarants of condominiums and subdivisions and require a public report or disclosure document to be approved before units or lots may be marketed, and some cities register owner-builders or require a permit-level registration of anyone acting as their own contractor. <b>Disclosure required</b>: the state or city requires no registration but requires a declaration — the owner-builder box on the permit application, an affidavit acknowledging the exemption and its limits, a notice to tenants before a conversion, a disclosure document delivered to buyers. <b>None</b>: the activity is captured by no register and no required declaration beyond the ordinary permit.</p>
   <p>The owner-builder exemption deserves its own paragraph because it is the one most often misread. Where a contractor licensing board exists, its statute typically exempts an owner building on their own property from holding a contractor licence — and then limits the exemption: by the kind of structure, by whether the owner intends to occupy, by whether the property is offered for sale within some window, by how many such projects an owner may undertake in a period, and by whether the owner hires licensed trades or acts as the employer of unlicensed workers. Every one of those limits is a figure or a condition the board publishes, and none of them is stated here. The exemption also does not reach the trades that must hold their own licences and pull their own permits regardless of who the owner is.</p>
   <p>The probe has a fixed order. The contractor licensing board’s page on owner-builder exemptions. The real-estate regulator’s chapter on subdivisions, condominiums and public reports, since the registration of a declarant often lives there rather than with the contractor board. The state’s new-home warranty or builder-registration programme, where one exists, which may be run by a consumer-affairs agency rather than either regulator. The city’s permit application form itself, because the declaration it requires is the city’s own disclosure rule. For each, write the outcome you landed in — registration, disclosure, none — or <i>no public record</i> where the question has no published answer, with the page and the date.</p>
   <p>Confirm the outcome and every limit on the exemption with the board or regulator that publishes it, and record the date.</p>
   <p class="src">Source to check: the state contractor board’s owner-builder exemption page and statute; the real-estate regulator’s subdivision and condominium chapter; any state builder-registration or new-home warranty programme; the city permit application’s owner-builder declaration. Date each outcome.</p>`,
   drill:{q:'A city’s permit application carries a box the property owner signs to declare that they are acting as their own contractor and understand the exemption’s limits. Which outcome is this, and where do the limits live?', opts:['Registration required: the signed box enrols the owner in the city’s register of owner-builders','Disclosure required: the declaration is the city’s rule, and the limits live with the state contractor board','None: a signature on a permit form is an acknowledgment, and the exemption carries no published limits','Registration required at the real-estate regulator, whose subdivision chapter governs owner-builders'], a:1, why:'A declaration on the permit is a disclosure requirement, not a register. The substance of the exemption — what an owner-builder may and may not do — is the contractor board’s, published in its statute and its page, and that is where the limits are read and dated.'}},

  {id:'dp5', t:'Bonds and guarantees as categories — what each protects, and who calls it', body:`
   <p>A development carries several promises that someone other than the promisor stands behind, and they are confused with one another constantly because the word <i>bond</i> is used for all of them. The structure to hold onto: a <b>surety bond</b> has three parties — the principal who must perform, the obligee who is protected, and the surety who pays if the principal does not — and the surety then recovers from the principal. A <b>guaranty</b> has two — a guarantor promises a beneficiary that someone else’s obligation will be met. <b>Insurance</b> is neither: it pays for a loss from a defined cause and does not seek recovery from the insured. Knowing which of the three a document is tells you who can call it and what happens afterwards.</p>
   <p>The surety bonds on a project are categories with fixed roles. The <b>performance bond</b> protects the owner (obligee) against the contractor (principal) failing to complete the contract; the owner calls it, and the surety may finish the work, pay for its completion, or pay up to the bond’s penal sum. The <b>payment bond</b> protects the subcontractors and suppliers who are owed money by the contractor; they call it, and because it gives them a source of payment it protects the owner from the liens they would otherwise file — on public work, where liens cannot attach to public land, the payment bond stands in for lien rights entirely. The <b>subdivision improvement bond</b> (or the agreement it secures) protects the city: the developer promises to build the public improvements — streets, water, sewer, drainage — and the city calls the bond if they are not built, releasing it in stages as the city accepts the work. <b>Maintenance or warranty bonds</b> protect the owner or city against defects for a period after completion. A <b>bid bond</b> protects the owner against a bidder who wins and then declines to sign.</p>
   <p>The <b>completion guarantee</b> is not a surety bond at all. It is the sponsor’s guaranty to the construction lender that the project will be completed — lien-free, on the approved plans, by a date — regardless of what the contractor does, and the lender is the one who calls it. It sits beside other lender guaranties (carry, repayment, non-recourse carve-outs) and is personal to the guarantor or to the entity named, which is why who signs it is a question for counsel before it is a question for this track.</p>
   <p>Verification follows the licensing track’s rule for insurance: the bond is confirmed with the surety directly, with you named as obligee or certificate holder, and the surety’s authority to write bonds in the state is confirmed with the state insurance regulator’s list of admitted sureties. <b>What this app does with it.</b> The contingency and reserve lines in the underwriting desk are the owner’s own money; a bond is someone else’s promise about someone else’s performance, and the completion guarantee is the reason the sponsor’s reserve exists at all — the development lab carries both as separate lines so that neither is mistaken for the other. Confirm each bond’s existence, obligee and penal sum with the surety and the regulator that admits it, and record the date.</p>
   <p class="src">Source to check: the state insurance regulator’s list of admitted sureties; the city’s subdivision improvement agreement and bond-release procedure; the construction loan agreement’s guaranty section for what the lender requires. Date each confirmation.</p>`,
   drill:{q:'A subcontractor has not been paid by the general contractor for work that is finished and inspected. Which instrument is built for this, and who calls it?', opts:['The payment bond: the subcontractor calls it, and a paid sub files no lien against the owner','The performance bond: the owner calls it, because an unpaid sub means the contract is not performed','The completion guarantee: the lender calls it, since an unpaid sub threatens lien-free completion','The subdivision improvement bond: the city calls it, because the inspected work is a public improvement'], a:0, why:'The payment bond exists for unpaid subcontractors and suppliers; they are its claimants, and its value to the owner is indirect because a paid sub files no lien. The performance bond is about the work, the completion guarantee is the sponsor’s promise to the lender, and the subdivision bond protects the city.'}},

  {id:'dp6', t:'Impact fees, exactions and conditions of approval — where they are published, when they fix, and why each is a sourced line', body:`
   <p>Three categories of cost arrive from the public side of a project, and they are mistaken for one another in pro formas written too early. <b>Impact fees</b> are charges adopted by ordinance to fund the public facilities new development uses — schools, parks, roads, water, sewer, fire — and the schedule is a published document, usually on the finance, planning or public-works department’s site, revised on a cycle the ordinance states. <b>Exactions</b> are what an approval requires the developer to give or do rather than pay: a dedication of land for a street or trail, a required share of affordable units or a fee in lieu, public art, undergrounding of utilities, off-site improvements, and utility connection or capacity charges set by the utility rather than the city. <b>Conditions of approval</b> are the numbered list attached to a discretionary approval, each one a task with a timing — <i>prior to issuance of grading permit</i>, <i>prior to issuance of building permit</i>, <i>prior to final inspection</i>, <i>prior to occupancy</i> — and some of them are the exactions in enforceable form.</p>
   <p>When a fee <b>fixes</b> is the question that decides whether the pro forma number is the real number. Depending on the state’s vesting rules and the local ordinance, a fee may be calculated at the schedule in effect on the date of application, on the date the permit is issued, or on the date it is paid; some cities freeze fees under a development agreement or a vesting map, and most do not freeze them at a pre-application estimate. The probe is a direct question to the department that collects the fee: <i>which event fixes this fee, and under which section?</i> The answer, with the section and the date, is the line. Utility charges have their own fixing rules set by the utility.</p>
   <p>Conditions of approval are read one at a time with four questions: who performs it, by which gate, what it costs, and whether it is already in the pro forma. The draft conditions appear in the staff report before the hearing; the adopted ones appear in the approval resolution after it; and the two can differ, because conditions are added and amended at the hearing. A condition that cannot be costed is an open item, not a zero.</p>
   <p><b>What this app does with it.</b> The feasibility gate wants each of these as a line with a source and a date rather than an allowance, because an allowance passes the gate and a sourced line can fail it, which is what the gate is for; the decision memo then cites the schedule, the section and the fixing event rather than restating the figure. Confirm every fee, exaction and condition with the department that imposes and collects it, and record the date.</p>
   <p class="src">Source to check: the adopted impact-fee schedule and its ordinance; the utility’s connection and capacity charge schedule; the staff report’s draft conditions and the adopted resolution’s final conditions; the section that states which event fixes each fee. Date each line.</p>`,
   drill:{q:'A pre-application estimate quoted a total for impact fees. The project applies for its building permit much later. Under this module, what fixes the fee actually due?', opts:['The pre-application estimate: the city is bound by the figure it quoted once the applicant relied on it','The lowest schedule published between the estimate and the permit, since the applicant may elect it','The fixing event the ordinance and state vesting rules name, put as a question to the collecting department','The staff report’s draft conditions, because fees become due only when a condition of approval names them'], a:2, why:'Pre-application estimates are rarely binding and schedules revise on a cycle. Which event fixes a fee — application, issuance, payment or a vesting instrument — is set by the ordinance and the state’s vesting rules, and the only reliable line is the department’s answer to that question, cited by section and dated.'}},

  {id:'dp7', t:'The lender’s side — the draw inspector, the title date-down, lien waivers, and conversion to permanent', body:`
   <p>A construction lender advances money against work in place, and the machinery it builds to do that safely is a second permission stack running beside the city’s. The developer who knows its parts can read a draw delay as a specific missing document rather than a mood. The <b>draw request</b> is a package: the pay application against the schedule of values, the invoices behind it, the lien waivers for the previous draw, the inspector’s report, and the title date-down. Each is a gate; a draw with any one missing waits.</p>
   <p>The <b>draw inspector</b> is the lender’s third party, not the city’s. The inspector walks the site and confirms that the work in place supports the amount requested against the schedule of values, that stored materials claimed are on site and insured, and that the remaining budget can finish the remaining work; where it cannot, the lender asks the sponsor to fund the shortfall before advancing — the <i>balancing</i> requirement in the loan agreement. The inspector also reads the permit record: an inspection the city failed is a line in the inspector’s report before it is anything else.</p>
   <p>The <b>title date-down</b> is the title company’s update of its search to the day of the draw, confirming that nothing has been recorded against the parcel since the last advance — no mechanic’s lien, no judgment, no notice — and endorsing the lender’s policy to cover the new advance. A recorded lien stops the date-down, which stops the draw, which is why <b>lien waivers</b> are collected before it: the contractor and each subcontractor and supplier sign a waiver of lien rights for the amount paid, in the categories every practitioner learns to tell apart — <b>conditional</b> (effective when the payment clears) and <b>unconditional</b> (effective on signing), each as a <b>progress</b> waiver for a period or a <b>final</b> waiver for the whole. Some states prescribe the form by statute and a waiver on any other form is not a waiver. The notice and lien record itself is public: preliminary notices, where the state uses them, and recorded liens both appear in the recorder’s index.</p>
   <p><b>Conversion</b> is the construction loan’s end. A loan written to convert to permanent financing lists the conditions in its agreement — the certificate of occupancy, a stated occupancy or income level, an updated appraisal, a debt-service test, no defaults, a final date-down and final waivers — and the loan converts when every one is met and not before; a loan written without conversion is repaid by a separate permanent loan whose lender runs its own list. Either way, the list is a category of open items with dates, and the interest reserve the construction loan carries is sized to a schedule that the conversion conditions can lengthen.</p>
   <p><b>What this app does with it.</b> The Record Locker is where the recorder’s index for the parcel is opened, so that a preliminary notice or a recorded lien surfaces as a dated public entry rather than a surprise at the date-down; the reserve line in the underwriting desk is the sponsor’s side of the balancing requirement. Confirm the recorded state of the parcel with the county recorder, and the loan’s draw and conversion conditions against the executed agreement, and record the date.</p>
   <p class="src">Source to check: the county recorder’s index for notices and liens against the parcel; the state’s statutory lien-waiver forms where they exist; the executed loan agreement’s draw, balancing and conversion sections. Date each.</p>`,
   drill:{q:'What does the title date-down do before a construction draw is funded?', opts:['Sets the date on which the construction loan converts to permanent, once the occupancy test is met','Confirms that the work in place supports the amount requested against the schedule of values','Records the previous draw’s lien waivers with the county so the recorder’s index shows them','Updates the title search to the day of the draw and endorses the lender’s policy to cover the new advance'], a:3, why:'The date-down is the title company’s check that nothing has been recorded against the parcel since the last advance, so the lender’s priority is intact at the moment it advances more money. The inspector confirms work in place; the waivers are what keep the date-down clean; conversion is a separate list at the loan’s end.'}},

  {id:'dp8', t:'Inspections as gates — the sequence, the failed inspection as a schedule event, correction notices, the final, and temporary versus final occupancy', body:`
   <p>An inspection is the moment the permit record and the building meet, and each one is a gate: work that must be inspected may not be covered until it passes. The sequence is set by the adopted code and the department’s own list, and it runs in a recognisable order wherever you are — footings and foundation, underground utilities, slab, framing, the rough stages of each trade (electrical, plumbing, mechanical, fire protection), insulation and energy, drywall or lath, the finals of each trade, and the final building inspection — with other departments interleaved: fire for alarm and suppression and access, public works for the right-of-way and the connections, health for a kitchen, planning for the conditions of approval that were tied to occupancy. The permit holder requests each inspection; the inspector records a result against the permit number.</p>
   <p>A <b>failed inspection</b> is first of all a schedule event. Nothing downstream of a covered-up element can proceed, so a failed framing inspection stops insulation, drywall and every finish behind it until the reinspection passes. The inspector issues a <b>correction notice</b>: a list of items, each tied to a code section, that must be corrected before reinspection is requested. Read it as a list of citations, respond to each, and keep the notice and the passed reinspection together in the file, because the lender’s draw inspector will read both. A <b>stop-work order</b> is the stronger instrument, posted when work proceeds without a permit or beyond its scope, and lifting it is a documented step with its own conditions.</p>
   <p>The <b>final inspection</b> closes the permit; the department’s status word becomes finaled or closed, and that is the word the next buyer’s permit search will read. The <b>certificate of occupancy</b> is a separate document issued when every department with a sign-off has given it, stating the use and occupancy the building is approved for; some jurisdictions issue a certificate of completion instead for work that does not change occupancy. A <b>temporary certificate of occupancy</b> is the pattern between the two: occupancy is permitted while listed items remain open, under stated conditions and for a stated period, and it expires. The open items and the expiry date are entries in the notebook with a next action, because a lapsed temporary certificate is a building being occupied without permission.</p>
   <p><b>What this app does with it.</b> The development lab’s gate sequence is this module at the project scale, and the contingency line is where a failed inspection lands — the reinspection fee, the uncovered work, the days the trades behind it waited — so that the gap between the modelled contingency and the one actually spent is a measurement the decision memo on the next project can cite. Confirm the inspection sequence, the correction notice’s requirements and every certificate’s conditions with the issuing building department, and record the date.</p>
   <p class="src">Source to check: the building department’s required-inspection list and request procedure; the correction notice and its cited sections; the department’s rules for temporary certificates of occupancy, including what expires and when. Date each entry.</p>`,
   drill:{q:'A building has a temporary certificate of occupancy with three listed open items and an expiry date. Under this module, how is it recorded?', opts:['As occupancy approved: the building is in use, and the listed items pass to the department’s own follow-up','As three open items and an expiry, each with a next action and a holder, since a lapse ends the permission','As a final certificate once tenants move in, because occupancy itself clears the conditions on the list','As the city’s problem: it issued the certificate, so it tracks the expiry and chases the open items'], a:1, why:'A temporary certificate is conditional and time-limited by design, and a lapsed one is a building occupied without permission. The notebook carries each open item and the expiry as live entries; the final certificate is a separate document the department issues only when the list is cleared.'}},

  {id:'dp9', t:'The public hearing — reading the agenda and staff report, speaking as the applicant, the record the decision rests on, and appeal windows', body:`
   <p>A discretionary approval is decided at a public hearing, and the hearing runs on documents published in advance. The <b>agenda</b> is posted under public-notice rules the city’s code states, and it tells you which body hears the item, where on the calendar it sits (a consent calendar item is approved without discussion unless pulled; a regular item is heard), and where the staff report is. The <b>staff report</b> is the document to read first and last: the project description, the analysis of the proposal against the <b>findings</b> the code requires the body to make before it can approve, the environmental determination, the public comments received, the staff recommendation, the draft conditions of approval, and the draft resolution. The findings are the hinge. A body may not approve without making them, and a denial is a statement that one of them could not be made — so every argument the applicant makes is an argument about a finding.</p>
   <p>Speaking as the applicant has a shape. The applicant or their representative presents, the public comments, the applicant responds, the body deliberates and votes. Speak to the findings and the conditions, not to taste; where the staff report contains an error of fact, submit the correction in writing before the hearing so it is in the record whether or not anyone reads it aloud; where a draft condition cannot be met, say which one and what the alternative is, because a condition adopted at the hearing is the one you will live with. The licensed professionals on the project speak to their own sheets. The developer speaks to the project and listens to the body, because the body’s questions are the findings it is unsure of.</p>
   <p>The <b>record</b> is everything before the body when the hearing closes: the staff report and its attachments, every written comment, every exhibit shown, the minutes or transcript, and the adopted resolution. An appeal is decided on that record, and what is not in it does not exist for the appellant or the applicant. This is why the written submission matters more than the spoken one, and why the resolution — with its findings and its final conditions — is pulled from the clerk and filed with the date it was adopted.</p>
   <p><b>Appeal windows</b> are a category to look up, never to assume. The code states who may appeal (the applicant, any person, only those who commented), to which body (a council, a board of appeals, a court), within what window after the decision, and whether the window runs from the vote, from the written decision, or from a notice of determination; it states the fee and the form. The approval is not final until the window closes without appeal or the appeal is resolved, and the lender’s counsel knows it, which is why the close of the appeal window is a date in the notebook and in the loan conditions. <b>What this app does with it.</b> The decision memo records the outcome, the findings relied on and the appeal-window close date; the Record Locker holds the adopted resolution and the staff report it rests on. Confirm the appeal rules with the clerk of the body that decided, and record the date.</p>
   <p class="src">Source to check: the municipal code’s public-notice and appeals sections; the agenda and staff report as posted; the adopted resolution from the clerk; the clerk’s own statement of when the appeal window closes. Date each.</p>`,
   drill:{q:'A planning commission votes to approve a project with conditions. For the purpose of relying on the approval, when does this track treat it as final?', opts:['When the appeal window the code states has closed without appeal, or an appeal has been resolved','At the vote: the commission is the deciding body, and its resolution is final the moment it is adopted','When the staff report is published with a recommendation to approve, since the findings are made there','When the building permit is applied for, because the building department then accepts the entitlement'], a:0, why:'A discretionary approval is appealable, and until the window closes the decision can be taken to another body. Who may appeal, to whom, within what period and from which date are the code’s to state and the clerk’s to confirm; the close date, looked up and recorded, is the entry that matters.'}},

  {id:'dp10', t:'The dated permission notebook — every approval, who issued it, the date, where it was verified, and what remains open', body:`
   <p>Everything in this track lands in one deliverable, and it is a notebook, not a certificate. Each row is an approval, a signature, an instrument or a gate; the columns are fixed. <b>The item</b>: zoning verification, pre-application letter, each discretionary approval and its conditions, the appeal-window close, plan check approval, the building permit and each trade permit, each required inspection, the temporary and final certificates of occupancy, each bond and its release, each fee and the event that fixed it, each professional seat and what it signed, each lender condition for draws and conversion, and the developer’s own registration or disclosure outcome. <b>The issuing authority</b>, by its exact name. <b>The instrument</b>: the letter, permit number, resolution number, certificate, bond number, receipt. <b>The date issued.</b> <b>Where you verified it</b>: the portal, the counter, the records request, the clerk, the surety, the recorder. <b>The date you verified it.</b> <b>The status</b>, in the issuing authority’s own word, or one of the honest ones this platform uses everywhere — <i>found</i>, <i>open</i>, <i>blocked</i>, <i>no public record</i>. <b>What remains open</b>, and <b>who holds the next action</b>.</p>
   <p>Why dated, in every column. Approvals expire if the permit is not pulled within the period the code states. Permits expire if no inspection is logged within the period the department states. Conditions of approval carry gates. Temporary certificates carry expiries. Bonds are released in stages. Fee schedules revise. A notebook row without a date is a rumour about a building, and a row whose verification date is old is a question, not an answer. The habit the track teaches is to re-verify at the moments that matter — before closing on the land, before the first draw, before each gate, before occupancy — and to write the new date rather than trusting the old one.</p>
   <p>What the notebook is not. It is not an approval; the issuing authority’s record is the approval, and the notebook is your dated index to it. It is not legal advice, and nothing in this track is; where a row raises a legal question — what an exemption permits, who signs a guaranty, whether a condition is lawful — the answer is a licensed attorney’s in that state. And completing this track confers <b>no licence, no registration, no degree, no accreditation and no continuing-education credit</b> with any board, department or regulator; the Trade School’s progress marks record that you read and drilled the material, and they mean nothing to the authorities named in your rows. If any page anywhere says otherwise, it is wrong.</p>
   <p><b>What this app does with it.</b> The public half of the notebook is pulled through the Permits &amp; code group in the record views; the dated copies of every instrument belong in the Record Locker; the development lab carries the gates in the order the rows will be filled; the feasibility gate reads the fee, exaction and condition rows as sourced lines; and the decision memo cites the notebook by row and date instead of restating what it says. Confirm every row with the authority that issued it, and record the date beside each one.</p>
   <p class="src">Source to check: the issuing authority named in each row — planning, building, clerk, recorder, surety, board, lender — every time; this platform is a dated map of where each publishes, and nothing more.</p>`,
   drill:{q:'What does completing this track confer, and what is the deliverable?', opts:['A developer registration recognised in the states that require one, filed on the learner’s behalf','Continuing-education credit toward a contractor licence, reported to the board on completion','No licence, registration, degree, accreditation or credit; the deliverable is the dated notebook','A provisional owner-builder exemption, valid until the contractor board issues its own declaration'], a:2, why:'The platform is education and navigation of the public record; it asserts no standing with any authority and conveys none. The deliverable is the notebook: every approval, its issuer, its instrument, its dates, where it was verified, and what remains open — checkable by anyone it is handed to.'}}
 ]};

function register(){
  if(!window.LXTS||!window.LXTS.TRACKS) return false;
  if(window.LXTS.TRACKS.some(t=>t.id===TRACK.id)) return true;
  window.LXTS.TRACKS.push(TRACK);
  return true;
}
register();
document.addEventListener('DOMContentLoaded', register);
window.LXTSDeveloper={register, TRACK};
})();
