/* locator.x — Trade School track: Licensing navigator — any state.
   Original curriculum written for locator.x. This track teaches licensing as a SYSTEM —
   how to read any state's regulator — and deliberately states no state's hour counts,
   fees or deadlines: the learner finds each number on the regulator's own page and
   records it with the date. Completing it confers no licence, degree, accreditation or
   continuing-education credit. Concatenated after tradeschool.js; registers itself into
   window.LXTS.TRACKS. */
(function(){
'use strict';

const TRACK={id:'license', name:'Licensing navigator — any state', who:'Anyone entering the trade, in any state', c:'--cat2',
 blurb:'Licensing taught as a system, not a state. How every regulator is built, what it publishes and in what order to read it, the salesperson-to-broker ladder as a pattern, portability, the adjacent licences, the duties every licence shares, and how to verify anyone before relying on them. You bring the numbers; this track teaches you where they live.',
 modules:[
  {id:'l1', t:'The regulator map — what every state publishes, and the order to read it', body:`
   <p>Every state in the United States has a body that licenses real-estate practice. It may be called a commission, a board, a department, a division or a bureau; it may sit inside a larger consumer-affairs agency or stand alone; its rules may come partly from the legislature (the statute) and partly from the regulator itself (the rules, plus the bulletins and position statements it issues between rule changes). The names differ. The <b>functions</b> do not: issue licences, keep the public register, discipline licensees, approve the schools that teach pre-licence courses, contract the exam vendor, and publish the rulebook. Once you can recognise those six functions on any regulator's site, you can navigate any state.</p>
   <p>Read the site in this order. <b>First, the licensee lookup.</b> Search a few names you know. The lookup teaches you the vocabulary before anything else does: what the licence types are called in this state, what statuses exist, how long a record stays visible. <b>Second, the disciplinary actions.</b> Read a dozen. They show what this regulator actually punishes, which is the fastest way to learn what it cares about. <b>Third, the rulebook and statute</b>, which you can now read because you know the words and the stakes. <b>Fourth, the approved-education-provider list</b>, because pre-licence education only counts when the provider is on it. <b>Fifth, the exam-vendor page</b> and its content outline, which is downstream of all of the above.</p>
   <p>The probe for this module is a page in your own notebook: the regulator's exact name, its address on the web, the licence types it issues, where each of the five publications lives, and <b>the date you looked</b>. A note without a date is a rumour, because regulators move pages, rename licence types and rewrite rules. When a publication cannot be found, write that too: <i>no public record found</i> is an honest status, and a far better one than a guess.</p>
   <p>Nothing in this module tells you what any state requires. It tells you where the state tells you. Confirm every requirement on the regulator's own page and record the date beside it.</p>
   <p class="src">Source to check: your state real-estate regulator's licensee lookup, disciplinary-action list and rulebook; the date you looked is part of the note.</p>`,
   drill:{q:'You open a regulator website you have never seen. Which publication does this track say to read first, and why?', opts:['The exam content outline — it tells you what to study, and therefore what the regulator thinks matters most','The approved-education-provider list — you need a school before anything else, and it fixes your timeline','The licensee lookup — it teaches the state’s licence types and statuses, so the rest becomes readable','The fee schedule — cost decides whether to proceed at all, so it is read before any rule is'], a:2, why:'The lookup is the vocabulary lesson: it names the licence tiers and statuses this state uses, which you need before the rulebook or exam outline will make sense. Schools and exams are downstream choices; reading them first means reading them without the words.'}},

  {id:'l2', t:'The ladder — salesperson to broker as a pattern, not a number', body:`
   <p>Strip away the state-specific figures and the licensing ladder is the same shape almost everywhere. <b>Eligibility</b>: an age floor, a background check, sometimes residency or fingerprinting. <b>Pre-licence education</b>: a set of hours from an approved provider, with named required courses. <b>The exam</b>: two portions, a national one on principles and practice shared across many states, and a state one on this state's law and rules; some states let you sit them together, some separately. <b>Sponsorship</b>: a new salesperson may not practise alone; the licence is held under a supervising broker who is answerable for the salesperson's conduct, and it goes inactive the day that association ends. <b>Experience</b>: a window of licensed, active practice before you may sit for the broker licence. <b>Broker education and exam</b>: more hours, more courses, a second exam. <b>Continuing education</b>: a cycle of required hours, often with mandated topics, before every renewal.</p>
   <p>The pattern varies at the edges. Some states have one licence called broker and everyone holds it; some have an associate-broker tier between salesperson and the broker who runs the office; some call the top seat managing broker or principal broker or designated broker. Some accept a degree or a related licence in place of part of the experience. The way to find your state's edges is to lay its licence types (from the lookup you read in the last module) against this pattern and note where they differ.</p>
   <p>Why the pattern exists is worth a paragraph, because it predicts how regulators behave. Sponsorship exists so that someone with experience is accountable for someone without it. The experience window exists so that the person who supervises others has seen enough transactions to recognise trouble. Continuing education exists because the rulebook changes and the regulator has no other way to make sure you read the changes. When you understand what a rule is protecting, you can usually guess where to find it and how strictly it is read.</p>
   <p>Your probe: for each rung — eligibility, education, exam, sponsorship, experience, broker education, continuing education — find <b>the number</b> on the regulator's own page (the hours, the window, the fee, the cycle), and write it down with the date and the address where you found it. The Trade School's California module carries sourced California figures measured on a stated date; it does not carry yours. This platform will not supply a number it has not measured; the notebook holds to the same rule. Confirm each requirement on the regulator's page and record the date.</p>
   <p class="src">Source to check: the regulator's examinee or applicant pages and the statute's licensing chapter; write every number with its date and page address.</p>`,
   drill:{q:'In the licensing pattern, what does “sponsorship” mean?', opts:['A current licensee writes a letter recommending you for the exam, which the regulator files with your application','Your licence is held under a supervising broker who answers for your conduct, and it goes inactive when that ends','Your brokerage pays your licensing fees and pre-licence education in exchange for a stated period of service','An experienced agent mentors you informally during your first year, with nothing filed at the regulator'], a:1, why:'Sponsorship is a legal relationship, not a social one: the salesperson practises only under a broker, and the regulator holds that broker answerable. That is also why the licence cannot stay active with no broker attached — there is no one responsible for it.'}},

  {id:'l3', t:'Portability — four categories, and how to tell which one a state uses', body:`
   <p>A licence is a creature of one state. Practising across a border is governed by a second state's rules about outsiders, and those rules fall into four distinct categories that are easy to confuse because the words are used loosely. <b>Reciprocity</b>: an agreement between named states. If your licence is from a state on the list, you may obtain this state's licence with part of the process waived — typically the national portion of the exam, sometimes the education — and the state portion still required. <b>Mutual recognition</b>: a broader rule that treats an active licence from any state (or any state meeting stated criteria) as satisfying part of the process, without a named list. <b>Cooperative licence</b>: a temporary or transaction-specific authorisation to work one deal in this state, usually in commercial property, and usually only alongside a licensed local broker who co-brokers and takes responsibility. <b>Physical-location rules</b>: rules about where you may be standing while you do the act — some states permit certain out-of-state activity provided it is conducted entirely from your own state, and treat setting foot in theirs as practising without a licence.</p>
   <p>The absence of all four is also an answer: some states require full licensure from everyone, with no waiver, and some distinguish residential from commercial. A state can use more than one category at once — reciprocity with a list of neighbours, plus a cooperative licence for commercial deals, plus a physical-location rule for everyone else.</p>
   <p>How to tell which applies. On the regulator's site, search for the words <i>reciprocity</i>, <i>reciprocal</i>, <i>recognition</i>, <i>cooperative</i>, <i>out-of-state</i> and <i>nonresident</i>. A page listing named states is reciprocity. A page saying any active licensee may apply is mutual recognition. An application form that must be signed by a local broker for a single transaction is a cooperative licence. The physical-location rule is usually hidden in the statute's definition of what it means to <i>engage in brokerage in this state</i>, so read that definition and its exemptions in full. Then write what you found, in which category, with the date.</p>
   <p>Nothing here says what any particular state allows. Confirm the category and its conditions on the regulator's own page, read the statute's definitions yourself, and record the date you did.</p>
   <p class="src">Source to check: the regulator's out-of-state or nonresident applicant page and the statute's definition of engaging in brokerage; note which of the four words it uses and the date.</p>`,
   drill:{q:'A regulator publishes a list of specific states whose licensees may skip the national portion of the exam and sit only the state portion. Which portability category is this?', opts:['Reciprocity — an agreement with named states','Mutual recognition — any active licensee qualifies','A cooperative licence — transaction-specific with a local broker','A physical-location rule — it governs where you may stand'], a:0, why:'The defining mark of reciprocity is the named list: the waiver follows from an agreement between particular states. Mutual recognition has no list, a cooperative licence is per transaction, and a physical-location rule says nothing about exams.'}},

  {id:'l4', t:'The adjacent roles — property management, lending, appraisal, inspection, contracting', body:`
   <p>The question <i>does this need a licence here?</i> comes up in five neighbouring trades, and each has its own pattern. <b>Property management</b> falls into three categories by state. In the first, managing property for others for compensation is defined as brokerage, so third-party management requires a broker's licence (or a salesperson working under one). In the second, the state issues a separate property-management licence or registration with its own rules. In the third, no licence is required, or the activity is exempt for certain people such as on-site employees of the owner. To tell which: read the statute's definition of brokerage and look for words like <i>leases, rents, or offers to lease or rent, for another, for compensation</i>; then read the exemptions list right after it.</p>
   <p><b>Mortgage origination</b> has a federal floor. The SAFE Act established that residential loan originators register or license through the <b>Nationwide Multistate Licensing System (NMLS)</b>, with a national test, background and credit review, and pre-licence and continuing education. The state layer sits on top: a state-specific education component, often a state test component, and a state licence whose issuing agency depends on the employer type — originators at depository institutions are typically registered rather than state-licensed, while those at independent companies hold state licences. The NMLS consumer lookup covers both.</p>
   <p><b>Appraisal</b> has a similar structure. Under the federal Title XI framework (FIRREA, 1989), the <b>Appraiser Qualifications Board (AQB)</b> sets national minimum criteria for each appraiser classification — education, experience, exam — and every state's appraiser board licenses at or above that floor, with the classifications stacked from trainee to certified general. <b>Home inspection</b> has no floor: some states license inspectors, some register them, some do nothing, and the regulator (where one exists) may be the real-estate commission or an entirely different board. <b>Contractors</b> come in three patterns too: a state licensing board with exams and bonding, local registration at the city or county with no state licence, or neither; the trigger is frequently the value or kind of work, which only the board's page can tell you.</p>
   <p>For each of the five, the probe is the same: find the regulator (it may not be the real-estate one), find the statute definition that captures the activity, find the exemptions, and write the category you landed in with the date. Confirm every requirement on that regulator's page; the pattern here is a map, not a ruling.</p>
   <p class="src">Source to check: the statute definition of brokerage and its exemptions for property management; NMLS for origination; the state appraiser board and the AQB criteria for appraisal; the state contractor board or local permit office for contracting. Date each.</p>`,
   drill:{q:'A state’s statute defines brokerage to include “leasing or renting real estate for another for compensation,” and the exemption list that follows mentions only owners managing their own property. Which property-management category is this state in?', opts:['Broker licence required for third-party management','A separate property-management licence, issued under its own chapter of the statute','No licence required — leasing for others is treated differently from selling for others','Cannot be determined from the statute alone; only the regulator’s guidance page settles it'], a:0, why:'When the brokerage definition captures leasing for others and the exemptions do not carve out managers, third-party management is brokerage and needs the broker licence. A separate PM licence would appear as its own chapter; a no-licence state would exempt the activity or never define it.'}},

  {id:'l5', t:'Fiduciary and disclosure duties — the spine every licence shares', body:`
   <p>Open the rulebook of any licence in this family and the same skeleton is there under different names. The classic set is six duties: <b>loyalty</b> (the client's interest above your own), <b>confidentiality</b> (what you learn in the relationship stays in it, including after it ends), <b>disclosure</b> (what you know that matters, told promptly), <b>obedience</b> (to lawful instructions — not unlawful ones), <b>reasonable care and skill</b> (the competence the licence implies), and <b>accounting</b> (every dollar of other people's money traced). Agents and brokers carry all six toward a client. The variations are instructive: an appraiser's rulebook replaces loyalty with <b>independence and impartiality</b>, because an appraiser who is loyal to a party has produced an advocacy document, not an appraisal. A loan originator's duties speak of acting in the borrower's interest and not steering toward a product for the originator's gain. A property manager's rulebook leans hardest on accounting.</p>
   <p>Disclosure is where the duties touch the public, and it has layers. <b>Agency disclosure</b>: who do you represent, told in writing before the relationship can be mistaken. <b>Material-fact disclosure</b>: conditions that would affect a reasonable person's decision, told regardless of which side you represent — states differ sharply on what counts as material, on stigmatised-property questions, and on what a seller's statutory disclosure form must contain. <b>Conflict and compensation disclosure</b>: any interest you hold in the deal, and who pays you. Some states permit a licensee to represent both sides with informed written consent; some forbid it; some allow a neutral facilitator role with reduced duties. Only the state's own rulebook can tell you which.</p>
   <p>The working test for every sentence you say to a counterpart: <i>whose interest does this serve?</i> A sentence that serves neither the client nor a disclosure the law requires is one the discipline leaves unsaid. The test is older than any statute, and it is the one test no exam administers; the disciplinary pages you read in the first module are where it is marked.</p>
   <p>The exact duty language, the agency-disclosure form and the material-fact standard are your state's to state. Read them on the regulator's page, not in a summary, and date the note.</p>
   <p class="src">Source to check: the duties chapter of your state's licence law and the regulator's required agency-disclosure form; the date you read them is part of the note.</p>`,
   drill:{q:'Which classic fiduciary duty does an appraiser’s rulebook replace with independence and impartiality — and why?', opts:['Accounting — appraisers do not handle client funds, so there is nothing for the duty to attach to','Loyalty — an appraisal owed to one party’s interest would be advocacy, not an opinion of value','Confidentiality — appraisals become public documents once filed with a lender or a court','Reasonable care — appraisal is judgment rather than skill, so care cannot be measured against it'], a:1, why:'The appraiser’s product is only useful if it is not loyal to anyone; lenders and courts rely on it precisely because the appraiser is not the client’s advocate. The other duties — care, confidentiality, accounting — survive in appraisal rules largely intact.'}},

  {id:'l6', t:'Fair housing — the federal floor, the local additions, and the discipline of the script', body:`
   <p>The federal Fair Housing Act (Title VIII of the Civil Rights Act of 1968, as amended in 1988) protects seven classes: <b>race, color, national origin, religion, sex, familial status, and disability</b>. That is the floor, and it applies in every state. States and cities build above it, and the additions vary widely: a state may add protections tied to how a tenant pays, to orientation or identity, to age, to marital or military status, to ancestry, or to characteristics no one would have predicted. A city may add more on top of its state. The only way to know the list where you practise is to read the state civil-rights statute and the city's ordinance, and to notice which agency enforces each — it is often not the real-estate regulator, though the regulator will discipline you for a violation all the same.</p>
   <p>A violation needs no slur. The conduct the statute reaches is <b>steering</b> (hinting that a buyer would be more comfortable somewhere else), <b>unequal information</b> (mentioning a feature to one caller and not another), <b>uneven screening</b> (criteria that bend for the applicant you liked), <b>advertising language</b> that describes who should live somewhere rather than what is there, <b>occupancy limits</b> that function as familial-status exclusions, and <b>refusals of reasonable accommodation or modification</b> for disability. None of these requires intent, and each is the kind of conduct a paired test — two callers, two profiles, one property — is built to find.</p>
   <p>The discipline licensees apply here is mechanical, which is its virtue. The answers to every question about a property are written once, and every prospect receives the same ones. The description is of the property and of third-party data sources, not of the people nearby. Screening criteria exist in writing before the first applicant appears and are applied in the order applications arrive, each decision recorded against them. A question that invites a characterisation of a neighbourhood's residents is met with the objective sources instead of the characterisation. A script is not evasion; it is the only proof that everyone was treated alike.</p>
   <p>Confirm your state's and city's protected-class lists and the enforcing agencies on their own pages, and record the date; these lists change, and the agency that enforces them is not always the one that licenses you.</p>
   <p class="src">Source to check: the federal statute's protected-class list, your state civil-rights statute, and the city ordinance; note the enforcing agency for each and the date.</p>`,
   drill:{q:'Which of the following is one of the seven federally protected classes?', opts:['Source of income','Familial status','Occupation','Credit history'], a:1, why:'Familial status — the presence of children under a stated age, pregnancy, and the process of obtaining custody — is one of the seven federal classes. Source of income is a common state or local addition, not a federal one; occupation and credit history are not protected classes at the federal level, though screening on them must still be applied evenly.'}},

  {id:'l7', t:'Trust accounting — other people’s money, and the case a regulator can prove from a bank statement', body:`
   <p>Earnest-money deposits, security deposits, rents collected for an owner, funds held pending a closing — every licence in this family touches money that belongs to someone else, and every rulebook treats it the same way. The pattern: client funds go into a <b>designated trust account</b> (the word may be <i>escrow</i> or <i>client</i> account) at a financial institution, titled so that the bank knows it holds trust money, kept wholly separate from the licensee's own operating account. Funds are deposited within a stated window after receipt. The licensee keeps a <b>journal</b> of every deposit and disbursement, a <b>ledger</b> for each beneficiary showing their balance, and reconciles all three — bank statement, journal, ledgers — on a stated cycle so that the sum of every ledger equals the journal equals the bank. Disbursement happens only on written authority (the contract, the lease, a release signed by the parties, or a court order), and the broker, not the salesperson, is responsible for all of it.</p>
   <p>Two words name the failures. <b>Commingling</b> is mixing: client money in the operating account, or your own money in the trust account beyond whatever small amount the state allows for bank charges. <b>Conversion</b> is using: paying any expense from trust funds, including briefly, including with every intention of replacing it on Friday. Neither requires a loss to a client. A perfectly balanced account that was in the wrong place for a week is a violation, and auditors find it because bank records do not forget.</p>
   <p>Why trust cases are the ones a regulator can bring unprompted is simple: this is the rule whose breach leaves a paper trail the regulator can read without a complaint. Fair-housing cases need a tester; disclosure cases need a dispute. Trust-account audits need only a bank statement. A trust case needs no theft; a sloppy bookkeeper, a slow month, and a broker who signed reconciliations without reading them are enough.</p>
   <p>The deposit window, the reconciliation cycle, the permitted personal balance and the record-retention rule are the numbers this module leaves blank on purpose: the regulator's page has them, and the date you read it belongs beside each one. The pattern is universal; the numbers are the state's.</p>
   <p class="src">Source to check: the trust-account or escrow chapter of the licence rules and the regulator's audit guidance; write each number with its date.</p>`,
   drill:{q:'A broker’s trust account balances to the penny, but for nine days last month a repair invoice for the office was paid from it and then reimbursed from operating funds. Under the trust-accounting pattern this is:', opts:['Acceptable — no client lost money, the account balances, and the office reimbursed it within the month','Conversion — trust funds were used for a non-trust purpose, regardless of repayment or loss','Commingling only — a bookkeeping error of the kind the permitted personal balance exists to absorb','A disclosure issue — the clients whose funds were touched were entitled to be told, and were not'], a:1, why:'Using trust money for any other purpose is conversion the moment it happens; repayment and the absence of loss are mitigation, not defence. Commingling is the related failure of mixing funds; this went further, because the money was spent.'}},

  {id:'l8', t:'Verifying any licensee before relying on them — and recording that you did', body:`
   <p>Before you rely on a broker, an inspector, a loan originator, an appraiser or a contractor, you check, and the check is the same six steps in every trade. <b>Look them up by name and licence number</b> on the regulator's register — not by the brand on the truck or the website, and not by a photograph of a card they show you. <b>Read the status</b>: active, inactive, expired, suspended, revoked, on probation — the exact words differ by state, and the lookup's own glossary explains them. <b>Match the licence type to the activity</b>: a salesperson licence is not a broker licence; a residential appraiser classification is not a commercial one; a contractor licensed in one trade may not hold another. <b>Check the expiry date</b>. <b>Read the discipline history</b>, which may be on a separate page from the lookup. <b>Confirm insurance and bonding</b> by asking for the certificate from the insurer or surety directly, with you named as certificate holder, rather than accepting a photocopy.</p>
   <p>For loan originators the register is NMLS's consumer lookup, which shows both state-licensed and federally registered originators and their employment history. For appraisers it is the state board's lookup. For contractors it is the state board or, where there is none, the local registration office — and where there is none of either, the honest note is <i>no public record</i>, which changes how much you rely on references and insurance.</p>
   <p>Then <b>record what you checked and when</b>: the register you used, the licence number, the status word, the expiry, whether discipline appeared, the insurer who confirmed coverage, and the date. Save the page as you saw it. Statuses change; last season's lookup proves nothing about today. The discipline re-checks at the moments that matter — before signing, before the first payment, before a deposit is released. A lookup that returns nothing is itself a finding: write <i>not found</i> rather than assuming a typo, and ask the person for the number as the regulator shows it.</p>
   <p>Each regulator defines its own status words. Confirm their meanings in that regulator's glossary, and record the date beside every check.</p>
   <p class="src">Source to check: the licensee lookup of the relevant regulator (real-estate commission, appraiser board, contractor board, or NMLS consumer access), the discipline page, and the insurer's certificate; date every entry.</p>`,
   drill:{q:'The regulator’s lookup shows a broker as “inactive.” For the purpose of relying on them in a transaction right now, you treat this as:', opts:['Equivalent to active — inactive just means the holder is between brokerages and may keep working meanwhile','Not currently licensed for the activity — the status word and the date go in the file','Revoked — the regulator has taken the licence for cause and the person may never hold one again','Expired — renewal is retroactive in every state, so the transaction proceeds as if the licence were active'], a:1, why:'Inactive licences exist in many states, and they share one feature: the holder may not practise under them until reactivated. Whatever the state’s precise definition, the status word on the register is what a later reader can check; what the person meant to do about it is not. Revoked and expired are different words with different consequences, and the register would have used them.'}},

  {id:'l9', t:'The developer’s professional stack — who carries a licence or a stamp, and how you check each', body:`
   <p>A development team is a set of seats, and most of them carry a licence, a seal, or a defined professional qualification that someone else relies on. <b>The architect</b> is licensed by a state architecture board; the seal on the drawings carries a licence number you can look up. <b>Engineers</b> — structural, civil, geotechnical, mechanical, electrical, plumbing — are licensed by a state engineering board, and each stamped sheet names the engineer responsible for it. <b>The land surveyor</b> holds a separate licence, usually from the same board as engineers or a sister board, and seals the boundary survey and the plat. <b>The general contractor</b> is licensed by a state board, registered locally, or neither, as the earlier module described. <b>Specialty trades</b> — electrical, plumbing, HVAC, fire protection — are often licensed separately from the general contractor, sometimes at the state level and sometimes by the city, and the permit office will tell you which trades must pull their own permits.</p>
   <p>One seat is different. The <b>Environmental Professional</b> who signs a Phase I environmental site assessment is not state-licensed for that role. The federal <i>All Appropriate Inquiries</i> rule defines who qualifies by a combination of credentials and experience, and the professional declares in the report itself that they meet the definition. You verify this seat by reading that declaration, checking the credentials it cites (which may themselves be state licences or professional certifications with their own lookups), and confirming that the report follows the current recognised standard. Whether a Phase I signed by someone outside that definition still supports the liability defences the rule is tied to is a legal question, which is exactly why the declaration is the first page a buyer reads.</p>
   <p>Verification for the stamped seats follows the last module's steps with one addition: <b>the stamp must match the work</b>. Look up the licence number printed on the seal, confirm the name matches, confirm the discipline matches the sheet (a civil engineer's seal on a structural sheet is a question to ask), confirm the status was active on the date the sheet was signed, and confirm the professional's insurance with the insurer. Keep a one-page register for the project: seat, name, regulator, licence number, status, date checked. The developer's own position belongs on that register too — some states exempt an owner building on their own land from contractor licensing and some do not, and the exemption's limits live in the statute.</p>
   <p>Each board, each licence type and each exemption is checked on that regulator's own page, never on the professional's say-so, and the project register carries the date of every check.</p>
   <p class="src">Source to check: the state architecture, engineering and surveying boards’ lookups; the contractor board or local permit office; the federal All Appropriate Inquiries definition of Environmental Professional and the declaration inside the Phase I report. Date each.</p>`,
   drill:{q:'How does a developer verify the Environmental Professional who signed a Phase I assessment?', opts:['Look them up on the state environmental board’s licensee register, exactly as for any other licensed professional on the team','Read the report’s own declaration under the federal All Appropriate Inquiries definition and check the credentials it cites','Confirm that a licensed engineer’s stamp appears on the report cover and on each figure, as it would on a structural sheet','Ask the title company to confirm the assessment was performed, since the title policy will insure over it'], a:1, why:'There is no state licence for the Environmental Professional role; qualification is defined federally and asserted in the report itself. The verification is therefore reading that declaration and checking the underlying credentials it relies on, each with its own regulator and lookup.'}},

  {id:'l10', t:'What this platform does and does not do', body:`
   <p>This track, and this platform, are <b>education and navigation of the public record</b>. The platform shows you how a regulator is built, what it publishes, and where to find what you need; it does not tell you what to do about it. Nothing here is legal advice, and nothing here replaces the regulator. Where this Trade School states a specific requirement — as the California module does — it names the source and the date it was measured, and tells you to verify before enrolling. Everywhere else it leaves the number blank on purpose, because an unmeasured number presented as fact is the one thing this platform refuses to produce.</p>
   <p>Completing this track confers <b>no licence, no degree, no accreditation, and no continuing-education credit</b>. The progress marks the Trade School keeps are a record that you read and drilled the material; they mean nothing to any regulator, and the platform asserts no standing with any. If a page anywhere claims otherwise, it is wrong and should be reported.</p>
   <p>What you leave this track with is a <b>licensing notebook</b>: the regulator for your state and for each adjacent trade, the address of each publication, the licence types and status words, every number you found on the regulator's own page with the date you found it, and an honest status against each probe — <i>found</i>, <i>blocked</i>, or <i>no public record</i>. That notebook is the thing of value. It is yours, it is dated, and it is checkable by anyone you hand it to.</p>
   <p>When you are ready to act — to enrol, to sit an exam, to hire a licensee, to practise across a line — the regulator's page and, where the question is legal, a licensed attorney in that state are the sources. Confirm there, and record the date.</p>
   <p class="src">Source to check: the regulator itself, every time; this platform is a map of where it publishes, dated, and nothing more.</p>`,
   drill:{q:'What does completing this track confer?', opts:['A certificate the state regulator recognises toward pre-licence education hours, where the state accepts online delivery','Continuing-education credit in states that accept online courses, once the regulator’s approval of the provider is on file','No licence, degree, accreditation or credit — a record that you studied, and the dated notebook you built','A provisional licence pending the state exam, valid for the window the regulator sets for first-time candidates'], a:2, why:'The platform is education and navigation of the public record; it asserts no standing with any regulator and conveys none. What the learner gains is knowledge of the system and a dated, checkable notebook of what each regulator publishes.'}}
 ]};

function register(){
  if(!window.LXTS||!window.LXTS.TRACKS) return false;
  if(window.LXTS.TRACKS.some(t=>t.id===TRACK.id)) return true;
  window.LXTS.TRACKS.push(TRACK);
  return true;
}
register();
document.addEventListener('DOMContentLoaded', register);
window.LXTSLicense={register, TRACK};
})();
