/* locator.x — Trade School deep track: property management as an operating discipline.
   Original curriculum written for locator.x. National in scope: every clock, cap or
   licence rule that depends on state or local law is named as a category the learner
   looks up with the regulator or statute — this file states no statutory number.
   Concatenated after tradeschool.js; registers itself into window.LXTS.TRACKS. */
(function(){
'use strict';
const L=()=>window.LX;

const TRACK={id:'pmdeep', name:'Property management — the operating discipline', who:'Owner-operators, managers and anyone hiring one', c:'--cat3',
 blurb:'What a manager actually controls, written down and measured: screening in order of receipt, the lease as a working document, the delinquency ladder, maintenance triage, the turn, reserves, trust accounting, the management agreement and the licence question. National in scope — every legal clock is a category you look up.',
 modules:[
  {id:'pd1', t:'What a manager actually controls', body:`
   <p>An owner buys a building; a manager runs an income statement. The distinction matters because almost everything on that statement is outside anyone’s control — the tax bill, the insurance market, the interest rate, the neighbourhood — and a manager is judged on the five lines that are not. <b>Economic occupancy</b> (rent actually collected ÷ rent the roll says is owed) rather than physical occupancy (units with a tenant in them), because a unit occupied by someone who stopped paying is a vacancy with a lock on it. <b>Collections</b>, the share of billed rent that arrives in the month billed. <b>Turn time</b>, days from move-out to the next rent-paying move-in. <b>Maintenance cost per unit</b>, repairs and routine upkeep, measured per door so buildings of different sizes compare. <b>Renewal rate</b>, the share of expiring leases that renew, because every non-renewal starts a turn.</p>
   <p>Each lever lands on a specific line of net operating income. Economic occupancy and collections set <i>effective gross income</i>: gross potential rent minus vacancy, minus credit loss, minus concessions. Turn time is the vacancy line made visible — one unit dark for thirty days is one-twelfth of that unit’s annual rent gone, and no later month gives it back. Maintenance cost per unit is an operating-expense line with a second, hidden effect: deferred repairs reappear as non-renewals, which reappear as turns. Renewal rate is the quiet one; it moves vacancy, turn cost and leasing fees at once, which is why a seasoned manager watches it before anything else.</p>
   <p>The discipline is to put a number on each lever every month, compare it with last month and with the underwriting that justified the purchase, and treat a gap as a question rather than a verdict. A manager who cannot produce the five numbers is not managing; they are collecting rent and waiting for the phone to ring. An owner who does not ask for them has delegated the asset rather than the task.</p>
   <p class="src">Source to check: the property’s own rent roll and trailing-twelve operating statement — the numbers come from there, not from a pro forma.</p>
   <p><b>What this app does with it.</b> The rent roll and actuals views sit beside the underwriting desk so that modelled rent and collected rent are two columns on the same page; the gap between them is the first number this module teaches you to ask for.</p>`,
   drill:{q:'A twelve-unit building shows all twelve units occupied, but two tenants have paid nothing for three months. Which statement is accurate?', opts:['Physical occupancy is 100% and so is economic occupancy','Physical occupancy is 100%; economic occupancy is roughly 83% and the two non-paying units are vacancies with locks on them','Economic occupancy cannot be below physical occupancy','The building is fully performing because the rent roll is full'], a:1, why:'Economic occupancy counts rent collected, not keys issued. Ten of twelve units are paying, so about 83% of the roll is real income; the other two are consuming turn time that has not started yet.'}},
  {id:'pd2', t:'Written screening criteria, applied in order of receipt', body:`
   <p>Screening is the point where fair-housing law stops being a poster and becomes a procedure. The procedure has three parts, and each exists to remove discretion from the moment when discretion is most dangerous. First, the <b>criteria are written before the unit is advertised</b>: the income-to-rent ratio the application must clear, how income is verified, what the credit report is checked for, what the rental-history reference must confirm, what in a background check is disqualifying and what is not, how applications are ranked when several arrive. Second, applications are <b>processed in the order they are received</b>, complete application and fee logged with a timestamp. Third, the <b>criteria are never changed while a queue exists</b>; if they need revising, the revision applies to the next vacancy.</p>
   <p>Why the sequence matters: a criterion invented after the first applicant arrives is, by construction, a criterion about that applicant. It may be innocent. It cannot be shown to be innocent, and a complaint investigator will ask exactly one question — were these rules in writing before this person applied? The written criteria are also the manager’s shield in the other direction: when an owner asks “can’t we just take the one who seemed nicer,” the answer is that the criteria decide, and the file shows that they did.</p>
   <p>The categories a screening standard must respect are set by federal law and expanded by many states and cities — source of income, criminal-history rules, occupancy standards and the handling of assistance animals vary by jurisdiction and change often. The discipline does not require you to memorise the list; it requires you to find the list that governs this address, record the date you read it, and write criteria that stay inside it. Every applicant who is declined receives the same written reason, drawn from the same written criteria, and the file keeps the application, the report and the decision together.</p>
   <p class="src">Source to check: the federal fair-housing protected classes plus your state and city additions, read on the agency’s own site, with the date you read it recorded in the file.</p>
   <p><b>What this app does with it.</b> The Record Locker is the place for the dated copy of your screening criteria and the governing protected-class list — so that when a decision is questioned, the rules that made it are retrievable with the date they were set.</p>`,
   drill:{q:'Three complete applications arrive for a unit on the same day. The owner, after meeting the second applicant, asks you to add a requirement that applicants have no pets. The correct move is:', opts:['Add it — the owner decides the standard','Apply it to the third applicant only, who has not been screened yet','Decline to change the criteria for this vacancy; note the request, and revise the written criteria for the next vacancy if the owner still wants it','Add it, but waive it for the first applicant as a courtesy'], a:2, why:'A rule added after applicants are in the queue is a rule about those applicants, and nothing in the file can prove otherwise. Criteria revise between vacancies, never inside one; the manager’s job is to hold that line for the owner’s protection as much as the applicant’s.'}},
  {id:'pd3', t:'The lease as an operating document', body:`
   <p>Owners read a lease once, at signing. Managers read it weekly, because it is the manual for every recurring decision on the property. The clauses that get used are a short list, and they are best learned as <b>categories</b> because the permitted content of each differs by state and sometimes by city. <b>Rent due date and grace period</b> — when rent is late, which starts every delinquency clock. <b>Late-fee pattern</b> — whether a fee is permitted at all, how it may be structured, whether it can compound; some jurisdictions cap it, some forbid certain forms, and the lease may only say what the law allows. <b>Entry notice</b> — how much warning the tenant receives before a non-emergency entry and what counts as an emergency. <b>Maintenance responsibility</b> — which repairs belong to the tenant, which to the owner, and how a request must be made and logged. <b>Renewal terms</b> — what happens at expiry: conversion to month-to-month, automatic renewal, required notice from each side.</p>
   <p>A lease earns its keep by answering a question before the question is asked. If a tenant reports a leak on a Friday evening and the manager has to call the owner to ask whether the lease treats plumbing as the owner’s repair, the lease has failed as an operating document even if it is legally perfect. The working test: for each of the five categories, can the manager, from the lease alone, state the rule in one sentence?</p>
   <p>Two cautions. Form leases bought generically may contain clauses that are unenforceable, or unlawful, in the state where the property sits; a clause the law does not allow is not a bargaining chip, it is a liability, and in some places its mere presence carries a penalty. And the lease is downstream of statute: where the two disagree, the statute wins, so the manager keeps a dated note of which state and local rules the lease was drafted against and revisits it when those rules change.</p>
   <p class="src">Source to check: your state’s landlord-tenant statute and any local ordinance for each of the five categories, plus the state association’s current form lease as a comparison — not as a substitute for reading the statute.</p>`,
   drill:{q:'Which of these is the best description of how a manager should learn the late-fee clause?', opts:['Memorise the national standard late fee and write it into every lease','Learn it as a category — whether a fee is permitted, how it may be structured, what caps apply — and look up the governing rule for each property’s jurisdiction','Copy the clause from a lease used in another state, since contract terms are portable','Leave the clause blank and decide case by case'], a:1, why:'There is no national standard; late-fee rules differ by state and city and change. A manager learns the category and the questions to ask, then reads the governing statute for the specific address and records the date.'}},
  {id:'pd4', t:'The delinquency ladder', body:`
   <p>Delinquency is managed as a sequence with a decision at every rung, never as a mood. The rungs, in order: <b>reminder</b> — a neutral, dated message the day after the grace period that states the amount and the due date, with no adjectives. <b>Notice</b> — the lease’s own late notice, in the form the lease and the law require, logged. <b>Payment plan</b> — offered, in writing, with dates and amounts, and only where the tenant’s situation suggests it will be kept; a plan that cannot be kept is a delay, not a remedy. <b>Formal notice</b> — the statutory notice that precedes a filing, in exactly the form, delivery method and timing the law prescribes, because a defect here resets everything. <b>Filing</b> — the court process, which from this point is run by the rules of the court and, in many places, by counsel.</p>
   <p>At each rung the manager decides one thing: proceed, pause, or step back to the previous rung. The decision is based on what the tenant has done — paid, communicated, gone silent — and recorded with a date. The ladder is the same for every tenant in the building, which is both the fair-housing requirement and the operational one: a tenant who learns that notices are sent to some neighbours and not others has learned that rent is negotiable.</p>
   <p>The clocks on the ladder — the grace period, the notice period before filing, the time a tenant has to respond, what a notice must say and how it must be served — are set by state statute and frequently by local ordinance, and they are among the most-litigated details in the trade. This module teaches the sequence; the numbers are yours to find. Look them up for the property’s jurisdiction, record the date you read them, and check again before each formal notice, because they change and a notice built on last year’s clock may be void.</p>
   <p class="src">Source to check: the state landlord-tenant statute and the local court’s own landlord-tenant pages for notice form, service method and timing; the date read goes in the file.</p>
   <p><b>What this app does with it.</b> The rent roll and actuals views show collections against billed rent each month, so a tenant climbing the ladder is visible as a collections gap before it becomes a vacancy; the Record Locker holds the dated notices.</p>`,
   drill:{q:'A tenant who has paid on time for three years misses rent and emails that a pay cheque was delayed a week. You have sent the reminder. The next rung is:', opts:['File immediately — the ladder exists to be climbed','Skip to formal notice to show you are serious','Decide: the communication and history suggest a dated, written payment arrangement is likely to be kept, so offer one in writing and log it; if it is missed, step to the lease notice','Do nothing until the lease notice period has passed'], a:2, why:'Each rung is a decision, not an automatic step. A communicating tenant with a clean history is the case a written payment plan is for; it is logged and dated so that, if it fails, the next rung is defensible.'}},
  {id:'pd5', t:'Maintenance triage and the work-order log', body:`
   <p>Every maintenance request is sorted into one of four classes the moment it arrives, and the class determines the response-time standard. <b>Emergency</b>: an active threat to life, safety or the structure — fire, flood, no heat in freezing weather, a gas smell, a door that will not secure; response is immediate and the tenant is told what to do while help is dispatched. <b>Urgent</b>: a loss of an essential service or a condition that will worsen quickly — no hot water, a non-working refrigerator, a roof leak in dry weather; response within a short, stated window. <b>Routine</b>: things that are broken but not consequential — a dripping tap, a sticking window; scheduled within a stated number of days and, where several accumulate, batched into one visit. <b>Deferred</b>: cosmetic or improvement items, placed on a list with a date and a reason, and reviewed at the next capital-planning pass rather than forgotten.</p>
   <p>Habitability is the legal floor under this system and it is non-waivable in most jurisdictions; what counts as an essential service, and how fast it must be restored, is defined by state and local law. The manager’s standards must sit inside those definitions, so the triage sheet records the governing habitability rules, and the date they were read, alongside the response targets.</p>
   <p>The <b>work-order log</b> is the evidence that the system ran. Each entry carries the date and time the request was received, the class assigned, who it was assigned to, the date and time of each response, what was done and what it cost, and the tenant’s confirmation that the issue is resolved. It serves three readers: the manager, who uses it to find the recurring faults that point to a capital item; the owner, who reads cost per unit from it; and, if it ever comes to that, a court or inspector, who will accept a contemporaneous log and discount a reconstruction.</p>
   <p class="src">Source to check: the state habitability standard and the local housing code for what is an essential service; the property’s own work-order log for the pattern.</p>`,
   drill:{q:'A tenant reports a slow drip under the kitchen sink on a Tuesday. Two other tenants have routine requests pending. The correct triage is:', opts:['Emergency — water damage is always an emergency','Urgent — anything involving water needs same-day attention','Routine — log it, schedule it within the stated window, and batch it with the other two routine items into one visit','Deferred — it is cosmetic'], a:2, why:'A slow drip is broken but not consequential and not worsening fast; it is routine. Batching routine work into one visit is where maintenance cost per unit is actually controlled, provided the log shows the stated window was met.'}},
  {id:'pd6', t:'The turn — the manager’s most controllable number', body:`
   <p>A turn is everything between one tenant’s keys coming back and the next tenant’s first rent payment. It has two costs, and the one most people count is the smaller. The visible cost is the <b>make-ready</b>: cleaning, paint, repairs, flooring where needed, locks, the leasing fee. The larger cost is the <b>days vacant</b>: every day the unit is dark is one day of that unit’s rent that will never be collected. Illustrative arithmetic only: a unit renting at 1,500 a month loses roughly 50 a day; a turn that takes thirty days instead of ten has cost 1,000 in rent before a single invoice is paid.</p>
   <p>The make-ready checklist is written once and used every time, in order: inspection against the move-in condition report within a day of keys back; the scope decided and trades booked the same day; cleaning and paint; repairs; final walk with photographs; the listing live, ideally before the paint is dry, with showings scheduled around the work. Each step has an owner and a target day. The checklist’s purpose is not thoroughness for its own sake; it is to remove the gaps between steps, because turns are lost in the waiting, not in the working.</p>
   <p>Turn days are the manager’s most controllable number because almost nothing about them depends on anyone else. The market sets the rent; the law sets the notice clocks; the roof decides when it leaks. But whether the painter is booked the day the keys come back is entirely a decision, and it shows up directly in the vacancy line. A manager who tracks average turn days by month, and explains any rise, is running the building; one who cannot say the number is being run by it.</p>
   <p id="ts_pd6live">Illustrative: a 1,500/month unit vacant for 30 days forgoes about 1,500 in rent before the make-ready invoices; cutting the turn to 10 days recovers roughly 1,000 of it.</p>
   <p class="src">Source to check: the property’s own turn history — dates out, dates in, make-ready invoices — not an industry average.</p>
   <p><b>What this app does with it.</b> The underwriting desk carries a vacancy assumption; the actuals view records what the turns actually cost. When the two diverge, the decision memo is where the owner writes down why, and what changes.</p>`,
   live:el=>{ try{
     const X=L(); const out=el.querySelector('#ts_pd6live'); if(!out) return;
     if(!X||!X.allListings){ out.innerHTML='Illustrative: a unit renting at 1,500 a month forgoes about 50 a day while vacant; a 30-day turn costs roughly 1,500 in rent before the make-ready invoices, and a 10-day turn about 500.'; return; }
     const l=X.allListings().filter(x=>(x.units||1)>=2).sort((a,b)=>(b.units||0)-(a.units||0))[0]||X.allListings()[0]; if(!l) return;
     const d=X.deal(l); const units=l.units||1; const perUnit=Math.round(d.rentMo/units); const perDay=perUnit/30;
     out.innerHTML=`Worked example on <b>${X.esc(l.addr)}, ${X.esc(l.city)}</b> (${units} units; indexed rent $${X.fmtN(d.rentMo)}/mo all units, about $${X.fmtN(perUnit)}/unit): one unit dark costs roughly $${X.fmtN(Math.round(perDay))} a day. A 30-day turn forgoes about $${X.fmtN(Math.round(perDay*30))}; a 10-day turn about $${X.fmtN(Math.round(perDay*10))}. The difference is the manager’s number. Rent here is an index estimate — replace it with the actual lease.`;
   }catch(e){} },
   drill:{q:'Why are turn days described as the manager’s most controllable number?', opts:['Because the law fixes them and the manager only has to comply','Because tenants decide when to leave','Because almost every day of a turn is set by scheduling decisions the manager makes alone, and each day lands directly on the vacancy line','Because they are the only cost the owner sees'], a:2, why:'Rent, clocks and the weather are outside the manager’s hands; whether trades are booked the day the keys come back is not. Turn days are lost in the waiting between steps, which is precisely what a checklist with owners and target days removes.'}},
  {id:'pd7', t:'Reserves and capital planning', body:`
   <p>A replacement reserve is a line on the operating statement, stated per unit per year, that funds the components a building consumes slowly: roof, heating and cooling plant, water heaters, paving, exterior paint, flooring, appliances. It is not maintenance — maintenance fixes what broke this month — and it is not optional in any underwriting that intends to survive the first roof. Lenders typically require one; owners who self-fund should hold one anyway, because the roof does not consult the owner’s preference.</p>
   <p>The number comes from a <b>component inventory</b>, not a rule of thumb. For each major component: what it is, when it was installed or last replaced, its expected useful life, its remaining life today, and an estimated replacement cost. Divide each component’s cost by its remaining years, add them up, divide by the unit count, and you have a reserve per unit per year that is defensible because it is built from the building rather than from a percentage. Illustrative arithmetic only: a roof estimated at 40,000 with eight years left contributes 5,000 a year; on a ten-unit building that is 500 per unit per year from the roof alone, before the mechanicals and the paving are added.</p>
   <p>The rule the trade learns slowly: <b>a reserve is a position, not a comfort</b>. It is money that exists, in an account, growing by the stated amount each month, and the owner statement shows the balance. A reserve that is “in the plan” but not in the account is a line of fiction, and the day the boiler fails it becomes a distribution cut, a loan, or deferred habitability — none of which the owner chose. The component inventory is revisited annually and after any major repair, and the reserve is reset to what it says.</p>
   <p class="src">Source to check: the property’s component inventory with installation dates from invoices and inspection reports; the lender’s reserve requirement if there is debt.</p>
   <p><b>What this app does with it.</b> The underwriting desk carries a reserve line as a per-unit assumption; this module is why it is there, and the component inventory you build is what replaces the default with the building’s own number.</p>`,
   drill:{q:'An owner statement shows “Replacement reserve: 300 per unit per year (budgeted)” but the reserve account balance is zero because the owner draws the full cash flow each month. The accurate description is:', opts:['The property is adequately reserved — the budget line exists','The reserve is a comfort, not a position; the building has no funded reserve and the first capital failure becomes a distribution cut, a loan or deferred work','The budget line satisfies the lender regardless of the account balance','Reserves are only needed for buildings over fifty units'], a:1, why:'A reserve exists only as money in an account. A budgeted amount that is distributed instead is not a reserve; it is a line that will be paid by whatever is nearest to hand when the component fails.'}},
  {id:'pd8', t:'Trust accounting and the owner statement', body:`
   <p>Money a manager holds for others — rent collected, security deposits, reserve balances — is not the manager’s money, and the accounting has to make that impossible to confuse. The first rule is <b>separate accounts</b>: client funds never sit in the manager’s operating account, and in many states a third-party manager is required by licensing law to hold them in a designated trust account with its own record-keeping, audit and reconciliation rules. Security deposits are frequently subject to further rules about where they are held and whether interest accrues; those rules are a category to look up for each state.</p>
   <p>The <b>monthly owner statement</b> has an anatomy, and a competent one has every part. The <i>rent roll</i>: each unit, tenant identifier, lease dates, rent due, rent collected, balance. <i>Collections</i>: total billed, total collected, delinquency with ageing. <i>Expenses</i>: each invoice, categorised, with the vendor and the work order it closes. <i>Reserves</i>: the contribution this month and the running balance in the account. <i>Distributions</i>: what was sent to the owner and when. <i>Open work orders</i>: everything not yet closed, with its class and age. A statement missing any part is a statement that cannot be reconciled, and an owner who accepts it has accepted not knowing.</p>
   <p><b>Reconciliation</b> is the monthly act of proving the statement against the bank: the trust account’s closing balance equals the sum of every owner’s and every tenant’s funds held, to the cent, with every difference explained and dated. Three-way reconciliation — bank statement, the ledger of funds held, and each individual client ledger — is the standard many regulators require of licensed managers and the standard an owner-manager should hold themselves to regardless. The reconciliation is kept with the statement, because a statement without one is an assertion.</p>
   <p class="src">Source to check: your state’s real-estate regulator’s trust-account rules for third-party managers; the state security-deposit statute for where deposits must be held; your own bank statement for the reconciliation.</p>
   <p><b>What this app does with it.</b> The rent roll and actuals views are built on the owner statement’s anatomy — billed, collected, expenses, reserve — so the statement your manager sends and the numbers the app shows are the same columns, and a missing column is visible.</p>`,
   drill:{q:'A manager’s monthly statement lists rent collected and expenses paid, with a net figure sent to the owner. Which single addition would most improve its usefulness as an operating document?', opts:['A cover letter describing the month','The reserve contribution and running reserve balance, open work orders with their age, and a reconciliation to the trust account','A larger font','A projection of next year’s rent growth'], a:1, why:'Collected minus expenses is an income summary, not an owner statement. Reserves, open work orders and the reconciliation are what let an owner tell whether the building is being run or merely drawn from.'}},
  {id:'pd9', t:'The management agreement — and the licence question', body:`
   <p>A management agreement is read for what it reveals, not for what it costs. <b>Fee patterns</b> come in a few shapes: a percentage of rent <i>collected</i> (the word matters — a percentage of rent <i>scheduled</i> pays the manager for vacancies); a leasing fee per new lease; a renewal fee; a mark-up on maintenance invoices or on in-house labour; sometimes a set-up fee or a minimum monthly fee. None of these is wrong. What matters is that every one is disclosed, that you can reconstruct the month’s fee from the statement, and that the structure rewards the outcomes you want — a manager paid mostly on leasing fees and maintenance mark-up has been given reasons to prefer turns and repairs.</p>
   <p>Then the operating clauses. <b>Term and termination</b>: how long, how it renews, what notice ends it, and whether a termination fee applies. <b>Authority limits</b>: the spending amount above which the manager must ask, who may sign leases and at what rent, who may start the delinquency ladder and who may file. <b>Insurance</b>: what the manager carries, what the owner must carry, and who is named on whose policy. <b>Trust-account handling</b> and the owner-statement cadence. <b>Exit mechanics</b>: how deposits, records, keys and open work orders transfer when the agreement ends. Read for the clause that is missing; a silent agreement is settled later by whoever has the better lawyer.</p>
   <p>Before any of that, the <b>licence question</b>. States fall into three broad categories for someone who manages property for others for compensation: those that require a real-estate broker licence (or work under a broker) for third-party management; those with a separate property-management licence or registration; and those that require none. Many states also exempt an owner managing their own property, and some extend the exemption to the owner’s salaried employee or to a resident manager, with conditions. The categories are stable; the details are not, and they are enforced. The check is simple: find the state real-estate regulator’s licensee search, look up the manager and the firm, and record the date you did it. An unlicensed third-party manager where a licence is required may be unable to enforce the fees in the agreement and may have exposed the owner too.</p>
   <p class="src">Source to check: the state real-estate commission’s licence requirements for property management and its public licensee search; the agreement itself, read against this module’s list of clauses.</p>
   <p><b>What this app does with it.</b> The Record Locker is where the signed agreement, the regulator’s licence search result and the date it was run belong together — the decision memo is where you record why this manager, on these terms.</p>`,
   drill:{q:'You are comparing two management proposals. One charges a percentage of scheduled rent; the other a slightly higher percentage of collected rent. Setting price aside, which observation about incentives is correct?', opts:['Scheduled-rent fees are better because they are simpler','A fee on scheduled rent pays the manager the same whether units are occupied or empty; a fee on collected rent pays only for rent that arrived, so the manager carries part of the vacancy and collections risk','There is no difference in practice','Collected-rent fees are a sign of an unlicensed manager'], a:1, why:'The word “collected” aligns the manager’s income with the owner’s. A fee on scheduled rent is earned on a vacant unit, which is exactly the outcome the owner most wants avoided.'}},
  {id:'pd10', t:'The KPI dashboard both sides see', body:`
   <p>A management relationship runs on one page that the manager and the owner both read every month, with the same definitions. The page is short on purpose. <b>Economic occupancy</b>: rent collected ÷ gross potential rent for the month. <b>Physical occupancy</b>: occupied units ÷ total units, shown beside it so that the gap between the two is the first thing seen. <b>Collections rate</b>: rent collected in the month ÷ rent billed in the month, excluding prior balances. <b>Delinquency</b>: balances owed, aged in buckets, as an amount and as a share of monthly billing. <b>Average turn days</b>: for turns completed this month and trailing twelve. <b>Turn cost per turn</b>: make-ready plus leasing fee, excluding capital items. <b>Renewal rate</b>: renewals ÷ expirations, trailing twelve. <b>Maintenance cost per unit</b>: routine repairs and upkeep for the month and trailing twelve, per door. <b>Open work orders</b>: count by class, with the oldest in each class. <b>Reserve balance</b>: in the account, against the component inventory’s target. <b>Net operating income</b>: the month and trailing twelve, beside the underwriting NOI the purchase was based on.</p>
   <p>Definitions are written down once and do not drift, because a KPI whose definition changes is not a KPI; it is a story. If “collections” begins to include prior-month catch-up payments, the rate will look better and mean less. The dashboard records its definitions at the bottom of the page, and a change to any of them is itself an entry with a date.</p>
   <p>How to read it: the dashboard is not a report card, it is an agenda. Each number that moved against its trailing twelve gets one sentence from the manager explaining why and one decision from the owner on what, if anything, changes. A dashboard nobody discusses is decoration. A dashboard where every number is green every month is either a very good building or a very good story, and the reconciliation from the trust-accounting module is how you tell which.</p>
   <p class="src">Source to check: the property’s own owner statements and work-order log, from which every figure on the page is derived — never a figure typed in from memory.</p>
   <p><b>What this app does with it.</b> The rent roll and actuals views hold the collected side of these definitions; the underwriting desk holds the modelled side; the reserve line and the decision memo close the loop by recording the target and the decision, so that both parties see one page built from the same records.</p>`,
   drill:{q:'The owner notices that the collections rate on the dashboard has improved for three months while the delinquency balance has barely moved. The most useful question is:', opts:['Why has delinquency not been written off yet?','Has the definition of collections changed — for example, to include catch-up payments on prior balances — so the rate improved while the underlying position did not?','Should the manager be paid a bonus for the improved rate?','Can the delinquency bucket be removed from the dashboard?'], a:1, why:'A KPI that improves while the thing it measures does not is usually a definition that moved. Collections should count the month’s billing only; the dashboard records its definitions so a drift like this is caught, not rewarded.'}}
 ]};

function register(){
  if(!window.LXTS||!window.LXTS.TRACKS) return false;
  if(window.LXTS.TRACKS.some(t=>t.id===TRACK.id)) return true;
  window.LXTS.TRACKS.push(TRACK); return true;
}
register();
document.addEventListener('DOMContentLoaded', register);
window.LXTSPMDeep={register, TRACK};
})();
